'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const historical=require('../presentation-v122/validate_historical_life'),art=require('./validate_reserved');
const SCRIPT='scripts/launcher_reserved_crew_art_browser_qa.js';
const REPORT='tools/launcher-room/presentation-v125/review-evidence/reserved-browser/RESERVED_ART_BROWSER_QA.json';
const SOURCES=Object.freeze(['launcher-reserved-crew.js','launcher-room.js','launcher-room-motion.js','launcher-room-motion-data.js','launcher-life-actions.js','launcher-life-data.js','launcher-room-dialogue.js','launcher-life.js','launcher-life-room.js','launcher-room.css','launcher.html']);
const NORMALIZATION='UTF-8 decoded text; replace CRLF (\\r\\n) with LF (\\n) only; no other changes.';
function checkNames(){return [1,2].flatMap(dpr=>[`dpr${dpr}-all-real-assets-native-decode-and-crop`,...art.DIRECTIONS.map(direction=>`dpr${dpr}-real-route-${direction}`),...art.KEYS.map(key=>`dpr${dpr}-selected-${key}-front-and-still`),`dpr${dpr}-same-scene-acting-life-presentation`]);}
function captureNames(){return [1,2].flatMap(dpr=>[...art.DIRECTIONS.flatMap(direction=>Array.from({length:9},(_,i)=>`dpr${dpr}-walk-${direction}-${String(i).padStart(2,'0')}`)),...art.KEYS.map(key=>`dpr${dpr}-selected-${key}`),...art.DIRECTIONS.flatMap(direction=>Array.from({length:8},(_,i)=>`dpr${dpr}-acting-${direction}-${i}`)),...['work','eat','rest','sleep','train'].flatMap(action=>Array.from({length:4},(_,i)=>`dpr${dpr}-life-${action}-${i}`))]);}
function capturePaths(report,reportPath=REPORT){assert.equal(reportPath,REPORT);return report.captures.map(item=>{assert.match(item.path,/^[a-z0-9-]+\.png$/);return path.posix.dirname(reportPath)+'/'+item.path;});}
function validate(root,report,reserved,evidence){
 assert.equal(report.schema,'one-piece-room-reserved-art-browser-qa/1');assert.equal(report.ok,true);assert.equal(report.status,'PASS');
 assert.equal(report.previewOnly,false,'Scratch or partial preview cannot replace actual four-character browser QA');assert.equal(report.humanAcceptance,false);
 assert.equal(report.autonomousLifeTickSuppressed,true,'Record scripted navigation conditions without claiming autonomous scenario acceptance');
 assert.equal(report.canvasReadbackOriginBypass,true,'Record actual isolated custom-scheme readback conditions');assert(/Actual headless Google Chrome DPR1\/2/.test(report.scope)&&/disables web security/.test(report.scope)&&/No physical-device/.test(report.scope));
 assert.deepEqual(report.keys,[...art.KEYS]);assert.deepEqual(report.dprs,[1,2]);assert.equal(report.assetCount,68);
 assert.equal(report.manifest?.path,art.MANIFEST,'Actual browser QA must bind final art manifest');art.readBound(root,report.manifest);
 assert.deepEqual(report.contactSheets,reserved.manifest.contactSheets,'Actual browser QA must bind all final contact sheets');
 assert.equal(report.sourceHashNormalization,NORMALIZATION);assert.deepEqual(Object.keys(report.sourceSha256||{}).sort(),[...SOURCES].sort());assert.deepEqual(Object.keys(report.sourceNormalizedSha256||{}).sort(),[...SOURCES].sort());
 for(const file of SOURCES){assert.match(report.sourceSha256[file],/^[a-f0-9]{64}$/);assert.equal(report.sourceNormalizedSha256[file],historical.normalizedSha256(fs.readFileSync(historical.safePath(root,'desktop/'+file))),'Actual art browser source changed: '+file);}
 assert.equal(report.testScriptSha256,historical.sha256(fs.readFileSync(historical.safePath(root,SCRIPT))),'Actual art browser script changed');
 assert.equal(report.fixtureOriginalSha256,historical.sha256(fs.readFileSync(historical.safePath(root,'scripts/launcher_radial_fixture.js'))));assert.match(report.fixtureEffectiveSha256,/^[a-f0-9]{64}$/);
 assert.deepEqual(report.assets.map(item=>item.path).sort(),[...art.ASSETS].sort(),'Actual browser must load all 68 final assets');
 const items=new Map(reserved.manifest.items.map(item=>[item.asset,item]));
 for(const asset of report.assets){const item=items.get(asset.path);assert.equal(asset.sha256,item.sha256);assert.equal(asset.bytes,item.bytes);assert.equal(asset.key,item.key);assert.equal(asset.kind,item.kind);assert.equal(asset.direction,item.direction);assert.equal(asset.action,item.action);assert.equal(asset.cell,item.cell);assert.equal(asset.frames,item.columns);assert.equal(asset.path,`public/images/launcher_room/reserved_v1/${asset.key}/${asset.relative}`);}
 assert.deepEqual(report.results.map(item=>item.name).sort(),checkNames().sort(),'Actual art browser must retain all 20 checks');assert(report.results.every(item=>item.status==='PASS'));
 const checks=new Map(report.results.map(item=>[item.name,item]));
 for(const dpr of [1,2]){
   const native=checks.get(`dpr${dpr}-all-real-assets-native-decode-and-crop`);assert.equal(native.assetCount,68);assert.equal(native.frameCount,324);assert.equal(native.frames.length,324);
   const seen=new Set();for(const frame of native.frames){const file=`public/images/launcher_room/reserved_v1/${frame.key}/${frame.relative}`,item=items.get(file);assert(item,'Unexpected browser frame asset');assert(Number.isInteger(frame.frame)&&frame.frame>=0&&frame.frame<item.columns);const id=file+':'+frame.frame;assert(!seen.has(id),'Duplicate native browser frame');seen.add(id);assert.deepEqual(frame.canvas,[item.cell,item.cell]);assert.equal(frame.differentChannels,0,'Production renderer differs from actual decoded crop');assert(frame.opaquePixels>0);assert.deepEqual(frame.bounds,item.frames[frame.frame].bounds,'Browser frame alpha bounds differ from imported pixels');}
   for(const direction of art.DIRECTIONS){const route=checks.get(`dpr${dpr}-real-route-${direction}`);assert.equal(route.samples.length,18);for(const key of art.KEYS){const samples=route.samples.flatMap(row=>row.dom.filter(actor=>actor.key===key&&actor.pose==='walk'&&actor.direction===direction));assert(samples.length>3,'Missing true route samples');assert(samples.every(actor=>actor.canvas[0]===384&&actor.canvas[1]===384));assert.equal(new Set(samples.map(actor=>actor.frame)).size,4,'Distance-driven walk must exhibit all four authored frames');}}
   for(const key of art.KEYS){const selected=checks.get(`dpr${dpr}-selected-${key}-front-and-still`);assert.equal(selected.before.key,key);assert.equal(selected.after.key,key);assert.equal(selected.before.attention,true);assert.equal(selected.after.attention,true);assert.equal(selected.before.direction,'south');assert.equal(selected.after.direction,'south');assert.equal(selected.before.x,selected.after.x);assert.equal(selected.before.y,selected.after.y);assert.equal(selected.dom.direction,'south');assert.equal(selected.dom.pose,'idle');assert.equal(selected.dom.source,'acting_v4');assert.deepEqual(selected.dom.canvas,[256,256]);}
   assert(/chosen explicitly, not autonomous AI behavior/.test(checks.get(`dpr${dpr}-same-scene-acting-life-presentation`).scope));
 }
 assert.deepEqual(report.captures.map(item=>item.name).sort(),captureNames().sort(),'All 184 actual room-stage captures are required');
 const captures=new Map(report.captures.map(item=>[item.name,item]));
 for(const [index,file] of capturePaths(report).entries()){const capture=report.captures[index];assert.equal(capture.path,capture.name+'.png');const proof=evidence.get(file);assert(proof?.kind==='screenshot','Actual art browser capture missing from frozen evidence');assert.equal(proof.sha256,capture.sha256,'Actual art browser capture changed');assert.deepEqual(proof.pixels,capture.dimensions);assert.equal(fs.statSync(historical.safePath(root,file)).size,capture.bytes);assert(capture.dimensions[0]>=512&&capture.dimensions[1]>=200);if(capture.name.startsWith('dpr2-')){const low=captures.get(capture.name.replace(/^dpr2-/,'dpr1-'));assert(low);assert(capture.dimensions.every((size,i)=>Math.abs(size-low.dimensions[i]*2)<=1),'DPR2 capture dimensions must reflect actual device scale');}}
 return {complete:true,checks:report.results.length,assets:68,framesPerDpr:324,dprs:2,captures:report.captures.length,humanAcceptance:false};
}
module.exports={validate,SCRIPT,REPORT,SOURCES,NORMALIZATION,checkNames,captureNames,capturePaths};
