'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),folder='C:/Users/王曜瑋/Documents/Codex/2026-04-20-1-2-start-html-game-html/handoffs/launcher-life-dialogue-expansion-20261008/';
const source=fs.readFileSync(folder+'proposal-v2.json'),d=JSON.parse(source),audit=JSON.parse(fs.readFileSync(folder+'audit-v2.json','utf8'));
assert.equal(audit.per_id.length,394);assert.equal(d.ready_solo_lines.length,273);assert.equal(d.ready_interactions.length,29);
const rows=d.ready_solo_lines.map(x=>({id:x.id,key:x.actor,scene:x.scene,line:x.text,mood:x.mood,pose:x.performance.speaker.clip,mode:x.performance.speaker.mode,furniture:x.furniture_key||'',durationMs:x.timing.speech_ms,cooldownMs:x.repeat.cooldown_seconds*1000,gapMs:x.repeat.actor_gap_seconds*1000,maxPerDay:x.repeat.max_per_active_day,transition:x.repeat.environment_transition_only,classification:x.classification}));
const pairs=d.ready_interactions.map(x=>({id:x.id,pair:x.actors,scene:x.scene,furniture:x.furniture_key||'',cooldownMs:x.repeat.cooldown_seconds*1000,pairCooldownMs:x.repeat.pair_gap_seconds*1000,maxPerDay:x.repeat.max_per_active_day,classification:x.classification,turns:x.turns.map(t=>({speaker:t.speaker,line:t.text,mood:t.mood,pose:t.performance.speaker.clip,durationMs:t.duration_ms,gapAfterMs:t.gap_after_ms,listener:{key:t.listener,pose:t.performance.listener?.clip||'listen'}}))}));
const acting=new Set(d.existing_animation_inventory.acting),life=new Set(d.existing_animation_inventory.life_common);
for(const r of rows){assert.equal(r.classification,'game_original');assert((r.mode==='life'?life:acting).has(r.pose));assert(r.line.length<=160);assert.notEqual(r.scene,'fish_handoff');}
for(const r of pairs)for(const t of r.turns){assert(acting.has(t.pose));assert(acting.has(t.listener.pose));assert(t.line.length<=160);}
const content={version:47,classification:'game_original',verifiedOriginalQuotes:0,rows,pairs};
fs.writeFileSync(path.join(__dirname,'integrated-v2.json'),JSON.stringify(content,null,2)+'\n');
fs.writeFileSync(path.join(__dirname,'acceptance-v2.json'),JSON.stringify({status:'EDITORIAL_AND_SCHEMA_ACCEPTED_RUNTIME_TEST_PENDING',sourceSha256:crypto.createHash('sha256').update(source).digest('hex'),reviewed:394,acceptedSolo:273,acceptedPairs:29,acceptedTurns:87,blockedIds:[...d.blocked_solo_lines,...d.blocked_interactions].map(x=>x.id),stagedNewActionIds:d.staged_new_actions.map(x=>x.id),verifiedOriginalQuotes:0,conditions:'Executable scene-specific adapter only; no evaluation of proposal condition strings; unknown context skips',limits:['39 new contact actions have no generated assets and are not loaded','All accepted lines are game-original adaptations; not verified original quotes']},null,2)+'\n');
const p=path.join(root,'desktop/launcher-room-dialogue.js'),s=fs.readFileSync(p,'utf8'),block='  // BEGIN ACCEPTED LIFE EXPANSION 47\n  const EXPANSION='+JSON.stringify(content)+';\n  // END ACCEPTED LIFE EXPANSION 47\n';
fs.writeFileSync(p,s.includes('// BEGIN ACCEPTED LIFE EXPANSION 47')?s.replace(/  \/\/ BEGIN ACCEPTED LIFE EXPANSION 47[\s\S]*?  \/\/ END ACCEPTED LIFE EXPANSION 47\r?\n/,block):s.replace('  const KEYS =',block+'  const KEYS ='));
console.log(JSON.stringify({solo:rows.length,pairs:pairs.length,turns:pairs.reduce((n,r)=>n+r.turns.length,0),blocked:20,staged:39}));
