'use strict';
// Real Chromium, production HTML/CSP/modules and real service over isolated SQL.
// Uses real wall time for rounds. Not a human playtest or live-account purchase.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {PGlite}=require(process.env.BOARD_QA_PGLITE||'D:/Codex_QA/draw-result-art-20260922/deps/node_modules/@electric-sql/pglite');
const runtimeBase=path.join(process.env.LOCALAPPDATA,'OpenAI/Codex/runtimes/cua_node');
const runtime=process.env.BOARD_QA_PLAYWRIGHT||fs.readdirSync(runtimeBase).map(name=>path.join(runtimeBase,name,'bin/node_modules/playwright')).find(file=>fs.existsSync(file));
const {chromium}=require(runtime);
const root=process.env.LAUNCHER_MINIGAMES_SOURCE_ROOT||path.resolve(__dirname,'..'),overlay=process.env.LAUNCHER_MINIGAMES_OVERLAY||root,out=process.env.LAUNCHER_MINIGAMES_QA_OUT||path.join(overlay,'tools/launcher-room/presentation-v127/review-evidence/minigames-client');
const source=file=>fs.existsSync(path.join(overlay,file))?path.join(overlay,file):path.join(root,file);
const temp=process.env.LAUNCHER_MINIGAMES_QA_TEMP||path.join(overlay,'tools/launcher-room/presentation-v127/browser-temp');fs.mkdirSync(out,{recursive:true});fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const B=require(path.join(root,'server/launcher-life-store')),S=require(path.join(root,'server/launcher-profile-shop')),db=new PGlite(),checks=[],captures=[],errors=[],commands=[];let tail=Promise.resolve(),seq=0,browser,server,page,context;
const pool={query:(...args)=>db.query(...args),async connect(){const previous=tail;let release;tail=new Promise(resolve=>release=resolve);await previous;return{query:(...args)=>db.query(...args),release};}};
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const sourceFiles=['desktop/launcher-room-minigames.js','desktop/launcher-room-minigames.css','desktop/launcher-life-room.js','desktop/auth-service.js','desktop/launcher.html','server/launcher-life-store.js','server/launcher-minigames.js','scripts/launcher_minigames_client_qa.js'];
const sourceHashes=()=>Object.fromEntries(sourceFiles.map(file=>[file,sha(fs.readFileSync(source(file)))]));
const cap={crewContentRevision:1};
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function add(secret){const keys=['robin','nami','ace','luffy'],today=new Date().toISOString().slice(0,10);await db.query('INSERT INTO player_profiles(secret,name,avatar,stats) VALUES($1,$1,$2,$3::jsonb)',[secret,'8',JSON.stringify({client:{totals:{coins:73}},launcherWalletV1:{coins:100,lastGrantDay:today},launcherOwnedV1:{items:keys.map(k=>'room-character-'+k)},launcherRoomV1:{revision:1,sceneId:'room-scene-default',capacityVersion:2,placements:[],characters:keys.map((k,i)=>({itemId:'room-character-'+k,x:160+i*70,y:440}))}})]);}
function fixture(){
  const initial={authenticated:false,profile:null,preferences:{},games:{}};
  window.onePieceDesktop={getState:async()=>initial,onState(){},onSocialState(){},onLauncherUpdate(){},onProgress(){},onSessionKicked(){},getSocialState:async()=>({ok:false}),getLauncherUpdateState:async()=>({ok:false}),getLauncherAnnouncements:async()=>({ok:false}),getLauncherShop:async()=>({ok:false}),getLauncherProfile:async()=>({ok:false}),getLauncherComments:async()=>({ok:false}),getLauncherLife:async()=>({ok:false})};
  window.__Q={user:'client-owner',offline:false,dropAnswer:false,hold:false,release:null,opens:0,closes:0,last:null,calls:[]};
}
async function capture(name){const file=name+'.png';await page.screenshot({path:path.join(out,file)});captures.push({path:file,sha256:sha(fs.readFileSync(path.join(out,file))),viewport:page.viewportSize()});}
async function state(){return page.evaluate(()=>__game.inspect());}
async function open(kind,key='nami'){await page.evaluate(({kind,key})=>__game.open({kind,characterId:'room-character-'+key}),{kind,key});}
async function start(){await page.getByRole('button',{name:'準備好了 · 開始挑戰'}).dblclick();await page.waitForFunction(()=>['showcase','answer','result','rewardPending'].includes(__game.inspect().phase));}
async function waitAnswer(){await page.waitForFunction(()=>__game.inspect().phase==='answer');}
async function close(){await page.getByRole('button',{name:'結束並關閉挑戰'}).click();const confirm=page.getByRole('button',{name:'結束並回房間'});if(await confirm.count())await confirm.click();await page.waitForFunction(()=>!__game.active());}
async function workRound(correct=true,{loseAck=false,timeout=false}={}){
  await waitAnswer();const prior=await state();
  const data=await page.evaluate(()=>__Q.last.minigame.challenge);
  if(!timeout){const indexes=data.crates.map((c,i)=>c.category===data.order.category?i:-1).filter(i=>i>=0);if(correct){for(const index of indexes)await page.keyboard.press(String(index+1));}else{const index=data.crates.findIndex(c=>c.category!==data.order.category);await page.keyboard.press(String(index+1));}if(loseAck)await page.evaluate(()=>__Q.dropAnswer=true);await page.keyboard.press('Enter');}
  await page.waitForFunction(index=>__game.inspect().roundIndex!==index||['result','retry'].includes(__game.inspect().phase),prior.roundIndex,{timeout:18000});
}
async function trainingRound(correct=true){await waitAnswer();const old=await state(),data=await page.evaluate(()=>__Q.last.minigame.challenge);for(const direction of correct?data.directions:data.directions.map(d=>d==='left'?'right':'left')){await page.keyboard.press({left:'ArrowLeft',up:'ArrowUp',right:'ArrowRight'}[direction]);await page.waitForTimeout(120);}await page.waitForFunction(index=>__game.inspect().roundIndex!==index||__game.inspect().phase==='result',old.roundIndex,{timeout:18000});}
async function main(){
 const before=sourceHashes();await db.exec('CREATE TABLE player_profiles(user_id SERIAL PRIMARY KEY,secret TEXT UNIQUE NOT NULL,name TEXT,avatar TEXT,stats JSONB,updated_at TIMESTAMPTZ DEFAULT now())');await add('client-owner');await add('client-second');await add('client-work-failure');
 server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\//,'')||'launcher.html';if(rel.includes('..')){res.writeHead(404);res.end();return;}const target=source('desktop/'+rel);if(!fs.existsSync(target)){res.writeHead(404);res.end();return;}const ext=path.extname(target);res.setHeader('Content-Type',ext==='.js'?'text/javascript':ext==='.css'?'text/css':'text/html');res.end(fs.readFileSync(target));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browserBase=path.join(process.env.LOCALAPPDATA,'ms-playwright');const executablePath=process.env.BOARD_QA_CHROMIUM||fs.readdirSync(browserBase).filter(n=>/^chromium-/.test(n)).sort().reverse().map(name=>path.join(browserBase,name,'chrome-win64/chrome.exe')).find(file=>fs.existsSync(file));
 browser=await chromium.launch({headless:true,...executablePath?{executablePath}:{},args:['--disable-gpu-shader-disk-cache']});context=await browser.newContext({viewport:{width:1280,height:850}});await context.addInitScript(fixture);await context.route('opui://**',route=>{const rel=decodeURIComponent(new URL(route.request().url()).pathname).replace(/^\//,''),target=source('public/'+rel);return !rel.includes('..')&&fs.existsSync(target)?route.fulfill({path:target}):route.fulfill({status:404,body:'missing'});});
 await context.exposeFunction('__serviceCommand',async(user,type,payload)=>{const snap=await B.getLauncherLife(pool,user,new Date(),cap);const result=await B.commandLauncherLife(pool,user,{type,payload,requestId:'client-real-'+String(++seq).padStart(8,'0'),expectedRevision:snap.life.revision},new Date(),cap);commands.push({user,type,ok:result.ok,error:result.error,roundIndex:result.minigame?.roundIndex,at:new Date().toISOString()});return result;});
 page=await context.newPage();page.on('pageerror',error=>errors.push(error.stack||error.message));await page.goto('http://127.0.0.1:'+server.address().port+'/launcher.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!window.OnePieceRoomMinigames);
 await page.evaluate(()=>{window.__game=OnePieceRoomMinigames.create({command:async(type,payload)=>{const owner=__Q.user;__Q.calls.push({type,owner});if(__Q.offline)return{ok:false,error:'offline'};const response=await __serviceCommand(owner,type,payload);if(__Q.hold)await new Promise(resolve=>__Q.release=resolve);if(type==='minigame.answer'&&__Q.dropAnswer){__Q.dropAnswer=false;return{ok:false,error:'offline'};}__Q.last=response;return response;},onOpen:()=>__Q.opens++,onClose:()=>__Q.closes++});});
 await check('intro-is-free-and-released-eleven-voices-only',async()=>{await open('work');assert.equal(commands.length,0);assert.equal(await page.evaluate(()=>Object.keys(OnePieceRoomMinigames.VOICES).length),11);assert.match(await page.locator('.room-minigame-cost').innerText(),/占用 1 次/);await capture('minigames-work-intro-desktop');});
 await check('double-start-consumes-one-shared-work-slot',async()=>{await start();assert.equal(commands.filter(c=>c.type==='minigame.start').length,1);const stats=(await db.query('SELECT stats FROM player_profiles WHERE secret=$1',['client-owner'])).rows[0].stats;assert.equal(stats.launcherCompanionsV1.workStartsToday,1);await db.query('UPDATE player_profiles SET stats=jsonb_set(stats,\'{launcherWalletV1,coins}\',\'495\'::jsonb) WHERE secret=$1',['client-owner']);});
 await check('work-mouse-toggle-keyboard-and-real-timeout',async()=>{await waitAnswer();const cargo=page.locator('.room-minigame-cargo').first();await cargo.click();assert.equal(await cargo.getAttribute('aria-pressed'),'true');await page.keyboard.press('1');assert.equal(await cargo.getAttribute('aria-pressed'),'false');await capture('minigames-work-active-desktop');await workRound(false,{timeout:true});assert.equal((await page.evaluate(()=>__Q.last.minigame)).correctRounds,0);});
 await check('lost-ack-retry-recovers-next-round-without-double-credit',async()=>{await workRound(true,{loseAck:true});assert.equal((await state()).phase,'retry');await page.getByRole('button',{name:'重新送出這一輪'}).click();await page.waitForFunction(()=>['showcase','answer'].includes(__game.inspect().phase));assert.equal((await state()).roundIndex,2);assert.equal((await page.evaluate(()=>__Q.last.minigame)).correctRounds,1);});
 await check('work-real-clock-wallet-full-preserves-and-spend-then-claim-once',async()=>{while((await state()).roundIndex<8&&(await state()).phase!=='result')await workRound(true);await page.waitForFunction(()=>__game.inspect().phase==='rewardPending',{},{timeout:20000});const attempts=commands.filter(c=>c.type==='minigame.finish').length;await page.waitForTimeout(1500);assert.equal(commands.filter(c=>c.type==='minigame.finish').length,attempts);await capture('minigames-wallet-full-desktop');await page.getByRole('button',{name:'保留成果，返回房間'}).click();const item=S.CATALOG.find(item=>item.type==='avatar'&&item.price>=10);const purchased=await S.changeLauncherItem(pool,'client-owner',item.id,'buy',cap);assert.equal(purchased.ok,true);await open('work');await start();await page.waitForFunction(()=>__game.inspect().phase==='result',{},{timeout:20000});assert.match(await page.locator('.room-minigame-rewards').innerText(),/10/);const current=await B.getLauncherLife(pool,'client-owner',new Date(),cap);assert.equal(current.wallet.coins,495-item.price+10);assert.equal(commands.filter(c=>c.type==='minigame.finish'&&c.ok).length,1);await capture('minigames-work-result-desktop');await close();});
 await check('training-whole-body-glows-before-input-and-keyboard-memory-play',async()=>{await open('training');await start();assert.equal((await state()).phase,'showcase');await page.keyboard.press('ArrowLeft');assert.equal((await state()).entered.length,0);await page.waitForFunction(()=>document.querySelector('.room-minigame-runner')?.dataset.wholeBody==='true');assert.equal(await page.locator('.room-minigame-runner').evaluate(canvas=>canvas.width),384);await capture('minigames-training-showcase-desktop');await trainingRound(false);await trainingRound(true);await trainingRound(true);await trainingRound(true);await page.waitForFunction(()=>__game.inspect().phase==='result',{},{timeout:15000});assert.match(await page.locator('.room-minigame-rewards').innerText(),/工作意願 \+5/);});
 await check('training-free-practice-survives-reward-cooldown-and-cancels',async()=>{await page.getByRole('button',{name:'再練一次 · 不領獎'}).click();assert.match(await page.locator('.room-minigame-cost').innerText(),/不消耗精神/);await start();assert.equal(await page.evaluate(()=>__Q.last.minigame.practice),true);await close();assert.equal((await B.getLauncherLife(pool,'client-owner',new Date(),cap)).activeMinigame,null);});
 await check('work-failure-retry-same-session-with-no-additional-cost',async()=>{await page.evaluate(()=>__Q.user='client-work-failure');await open('work','nami');await start();while((await state()).phase!=='result')await workRound(false);const failed=await page.evaluate(()=>__Q.last.minigame);assert.equal(failed.state,'failed');await page.getByRole('button',{name:'再試一次 · 不額外消耗'}).click();await page.waitForFunction(()=>__game.inspect().phase==='showcase');assert.equal(await page.evaluate(()=>__Q.last.minigame.id),failed.id);assert.equal(await page.evaluate(()=>__Q.last.minigame.attempt),2);const stats=(await db.query('SELECT stats FROM player_profiles WHERE secret=$1',['client-work-failure'])).rows[0].stats;assert.equal(stats.launcherCompanionsV1.workStartsToday,1);await close();});
 await check('narrow-390px-layout-all-controls-and-cancel-before-start',async()=>{await page.setViewportSize({width:390,height:844});await page.evaluate(()=>__Q.user='client-second');await open('training','ace');await capture('minigames-training-intro-narrow');const card=await page.locator('.room-minigame-card').boundingBox();assert(card.x>=0&&card.x+card.width<=390);const count=commands.length;await close();assert.equal(commands.length,count);});
 await check('narrow-touch-sized-directions-and-explicit-cancel',async()=>{await open('training','ace');await start();await waitAnswer();await capture('minigames-training-active-narrow');for(const b of await page.locator('.room-minigame-direction').all()){const rect=await b.boundingBox();assert(rect.width>=44&&rect.height>=43);}await page.getByRole('button',{name:'左側',exact:true}).click();assert.equal((await state()).entered.length,1);await close();assert.equal((await B.getLauncherLife(pool,'client-second',new Date(),cap)).activeMinigame,null);});
 await check('dismiss-during-start-does-not-reopen-under-another-account',async()=>{await open('work','ace');await page.evaluate(()=>__Q.hold=true);await page.getByRole('button',{name:'準備好了 · 開始挑戰'}).click();await page.waitForFunction(()=>!!__Q.release);await page.evaluate(()=>{__game.dismiss();__Q.user='client-owner';__Q.hold=false;__Q.release();});await page.waitForTimeout(300);assert.equal((await state()).phase,'closed');assert.equal(await page.locator('#roomMinigameOverlay').isHidden(),true);});
 await check('rendered-assets-and-plaintext-no-page-errors',async()=>{assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>Object.values(OnePieceRoomMinigames.VOICES).every(v=>['name','work','training','win'].every(k=>typeof v[k]==='string')&&['good','miss'].every(k=>Array.isArray(v[k])&&new Set(v[k]).size>=3))),true);assert.equal(await page.evaluate(()=>[...document.querySelectorAll('#roomMinigameOverlay img')].filter(img=>!img.complete||!img.naturalWidth).length),0);assert.deepEqual(sourceHashes(),before);});
 const report={schema:'launcher-minigames-client-qa/1',status:'PASS',createdAt:new Date().toISOString(),checks,counts:{passed:checks.length,failed:0},sourceSha256:before,captures,commands,limitations:['Automated Chromium interaction, not human playtest.','Real service functions and isolated PGlite; no production account or PostgreSQL transport claim.','Real wall-clock rounds; fixture reads current challenge for deterministic inputs.','Module mounted in production HTML; root release checks room-wheel integration separately.']};fs.writeFileSync(path.join(out,'MINIGAMES_CLIENT_QA.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,passed:checks.length,report:path.join(out,'MINIGAMES_CLIENT_QA.json')}));
}
main().catch(error=>{fs.writeFileSync(path.join(out,'MINIGAMES_CLIENT_FAILURE.json'),JSON.stringify({status:'FAIL',error:error.stack,checks,commands},null,2));console.error(error);process.exitCode=1;}).finally(async()=>{await browser?.close();await new Promise(resolve=>server?server.close(resolve):resolve());await db.close();});
