'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {PGlite}=require(process.env.BOARD_QA_PGLITE||'D:/Codex_QA/draw-result-art-20260922/deps/node_modules/@electric-sql/pglite');
const B=require('../server/launcher-life-store'),S=require('../server/launcher-profile-shop');
const db=new PGlite(),checks=[];
let transactionTail=Promise.resolve(),seq=0;
// One-session PGlite: queue whole transactions. This verifies both service
// orderings and idempotency; it does not claim production PostgreSQL lock tests.
const pool={query:(...args)=>db.query(...args),async connect(){const prior=transactionTail;let release;transactionTail=new Promise(resolve=>release=resolve);await prior;return{query:(...args)=>db.query(...args),release};}};
const cap={crewContentRevision:1},today=new Date().toISOString().slice(0,10),base=Date.parse(today+'T03:00:00.000Z');
const now=s=>new Date(base+s*1000),id=key=>'room-character-'+key;
const check=(name,actual,expected)=>{assert.deepEqual(actual,expected,name);checks.push({name,status:'PASS'});};
function stats(keys=['luffy','zoro','nami'],coins=100){return{client:{totals:{coins:73}},board:{saved:'preserve'},launcherWalletV1:{coins,lastGrantDay:today},launcherOwnedV1:{items:keys.map(id)},launcherRoomV1:{revision:1,sceneId:'room-scene-default',capacityVersion:2,placements:[],characters:keys.map((key,i)=>({itemId:id(key),x:160+i*70,y:440}))}};}
const add=async(secret,value=stats())=>db.query('INSERT INTO player_profiles(secret,name,avatar,stats) VALUES($1,$1,$2,$3::jsonb)',[secret,'8',JSON.stringify(value)]);
const row=async secret=>(await db.query('SELECT * FROM player_profiles WHERE secret=$1',[secret])).rows[0];
const get=(secret,t=0)=>B.getLauncherLife(pool,secret,now(t),cap);
async function cmd(secret,type,payload,t=0,options={}){const snap=options.snapshot||await get(secret,t);return B.commandLauncherLife(pool,secret,{type,payload,requestId:options.requestId||'minigame-qa-'+String(++seq).padStart(8,'0'),expectedRevision:options.revision??snap.life.revision},now(t),cap);}
const ref=session=>({sessionId:session.id,token:session.token});
const start=(secret,kind='work',characterId=id('luffy'),t=0,extra={})=>cmd(secret,'minigame.start',{kind,characterId,...extra},t);
async function play(secret,response,t=0,wrong=0){let session=response.minigame;while(session.challenge){const round=session.challenge;t=Math.max(t,(Date.parse(round.notBefore)-base)/1000);const input=session.kind==='work'?{selections:round.crates.filter(crate=>crate.category===round.order.category).map(crate=>crate.id)}:{directions:round.directions};if(wrong-->0)input[session.kind==='work'?'selections':'directions']=[];response=await cmd(secret,'minigame.answer',{...ref(session),roundId:round.id,...input},t);assert.equal(response.ok,true,JSON.stringify(response));session=response.minigame;}t=Math.max(t,(Date.parse(session.finishNotBefore)-base)/1000);return{response:await cmd(secret,'minigame.finish',ref(session),t),t};}
async function main(){
 await db.exec('CREATE TABLE player_profiles(user_id SERIAL PRIMARY KEY,secret TEXT UNIQUE NOT NULL,name TEXT,avatar TEXT,stats JSONB,updated_at TIMESTAMPTZ DEFAULT now())');
 await add('owner');await add('visitor',stats([]));
 check('bad identity rejected',(await B.commandLauncherLife(pool,'bad',{type:'minigame.start'},now(0),cap)).error,'bad secret');
 check('unowned actor rejected',(await start('visitor')).error,'not_owned');
 check('forged reward rejected',(await start('owner','work',id('luffy'),0,{reward:999})).error,'invalid_command');
 check('work cannot disguise rewarded practice',(await start('owner','work',id('luffy'),0,{practice:true})).error,'invalid_minigame');
 check('unknown game rejected',(await start('owner','jackpot')).error,'invalid_minigame');
 const first=await start('owner');const initial=first.minigame;
 check('work challenge begins at round zero',initial.roundIndex,0);
 check('only current challenge exposed',Object.hasOwn(initial,'rounds'),false);
 check('work always has three crates',initial.challenge.crates.length,3);
 check('opening game does not earn money',first.wallet.coins,100);
 check('starting game reserves shared work allowance',(await row('owner')).stats.launcherCompanionsV1.workStartsToday,1);
 check('starting game reserves per-character allowance',(await row('owner')).stats.launcherCompanionsV1.characters[id('luffy')].worksStartedToday,1);
 check('get returns active session for reconnect',(await get('owner')).activeMinigame.id,initial.id);
 check('another game shares single active slot',(await start('owner','training',id('zoro'))).error,'minigame_active');
 check('legacy start sees interactive session',(await S.startLauncherCharacterWork(pool,'owner',id('luffy'),now(0),cap)).error,'minigame_active');
 check('new background reserve sees interactive session',(await cmd('owner','work.reserve',{itemId:id('luffy'),stationId:'deck',roomRevision:1})).error,'minigame_active');
 check('autonomous activity cannot fake rest while playing',(await cmd('owner','activity.record',{itemId:id('luffy'),activity:'Rest'},10)).error,'minigame_active');
 check('different owner cannot cancel session',(await cmd('visitor','minigame.cancel',ref(initial))).error,'invalid_minigame_session');
 check('wrong session token rejected',(await cmd('owner','minigame.cancel',{...ref(initial),token:'f'.repeat(48)})).error,'invalid_minigame_session');
 const answer={...ref(initial),roundId:initial.challenge.id,selections:initial.challenge.crates.filter(c=>c.category===initial.challenge.order.category).map(c=>c.id)};
 check('server prevents skipping round pacing',(await cmd('owner','minigame.answer',answer,0)).error,'minigame_too_early');
 check('server rejects premature finish',(await cmd('owner','minigame.finish',ref(initial),1)).error,'minigame_incomplete');
 check('client cannot supply score',(await cmd('owner','minigame.answer',{...answer,score:999},3)).error,'invalid_command');
 check('unknown crate ID rejected',(await cmd('owner','minigame.answer',{...answer,selections:['forged']},3)).error,'invalid_minigame_answer');
 check('duplicate crate ID rejected',(await cmd('owner','minigame.answer',{...answer,selections:[answer.selections[0],answer.selections[0]]},3)).error,'invalid_minigame_answer');
 const answered=await cmd('owner','minigame.answer',answer,3,{requestId:'answer-once-1234'});
 check('one correct round counted',answered.minigame.correctRounds,1);
 check('repeated request does not add round',(await cmd('owner','minigame.answer',answer,3,{requestId:'answer-once-1234'})).minigame.correctRounds,1);
 check('fresh request cannot replay answered round',(await cmd('owner','minigame.answer',answer,3)).error,'minigame_round_conflict');
 const won=await play('owner',answered,3);
 check('successful work awards existing ten coins',won.response.wallet.coins,110);
 check('successful work returns fixed reward',won.response.minigame.result.coins,10);
 check('successful work gives one affinity',(await row('owner')).stats.launcherCompanionsV1.characters[id('luffy')].affinity,1);
 check('work ledger receipt uses existing namespace',won.response.receipt.operationId.startsWith('life-work:minigame-'),true);
 check('repeated finish returns same receipt',(await cmd('owner','minigame.finish',ref(initial),won.t+1)).receipt,won.response.receipt);
 check('repeated finish does not mint coins',(await get('owner',won.t+1)).wallet.coins,110);
 check('legacy life completion cannot double claim',(await cmd('owner','work.complete',{jobId:won.response.receipt.jobId},won.t+1)).wallet.coins,110);
 check('successful session cannot retry',(await cmd('owner','minigame.retry',ref(initial),won.t+1)).error,'minigame_completed');
 check('private session absent from friend projection',Object.hasOwn(await B.publicProjection(pool,await row('owner')),'activeMinigame'),false);
 check('Card coins preserved',(await row('owner')).stats.client.totals.coins,73);
 check('Board save preserved',(await row('owner')).stats.board,{saved:'preserve'});
 await add('retry');let attempt=await start('retry');let failure=await play('retry',attempt,0,8);
 check('failed work receives zero coins',failure.response.wallet.coins,100);
 check('failed attempt retains session slot',failure.response.minigame.state,'failed');
 check('failed attempt offers two retries',failure.response.minigame.result.attemptsRemaining,2);
 check('failed session blocks parallel work',(await S.startLauncherCharacterWork(pool,'retry',id('luffy'),now(25),cap)).error,'minigame_active');
 let retry=await cmd('retry','minigame.retry',ref(attempt.minigame),failure.t+1);
 check('retry retains same session id',retry.minigame.id,attempt.minigame.id);
 check('retry uses second attempt',retry.minigame.attempt,2);
 check('retry does not consume extra daily start',(await row('retry')).stats.launcherCompanionsV1.workStartsToday,1);
 failure=await play('retry',retry,failure.t+1,8);retry=await cmd('retry','minigame.retry',ref(retry.minigame),failure.t+1);
 const retryWin=await play('retry',retry,failure.t+1);
 check('third attempt can succeed once',retryWin.response.wallet.coins,110);
 check('third attempt still uses one work slot',(await row('retry')).stats.launcherCompanionsV1.characters[id('luffy')].worksStartedToday,1);
 await add('three-fails');attempt=await start('three-fails');let time=0;
 for(let n=0;n<3;n++){failure=await play('three-fails',attempt,time,8);time=failure.t+1;if(n<2)attempt=await cmd('three-fails','minigame.retry',ref(attempt.minigame),time);}
 check('third failure closes session',failure.response.minigame.state,'completed');
 check('third failure cannot replay fourth attempt',(await cmd('three-fails','minigame.retry',ref(attempt.minigame),time)).error,'minigame_completed');
 check('three failed attempts never pay',(await get('three-fails',time)).wallet.coins,100);
 await add('cancel');const cancelledStart=await start('cancel');
 check('cancel closes session',(await cmd('cancel','minigame.cancel',ref(cancelledStart.minigame),1)).minigame.state,'cancelled');
 check('cancel then finish cannot claim',(await cmd('cancel','minigame.finish',ref(cancelledStart.minigame),40)).error,'minigame_cancelled');
 check('cancel preserves wallet',(await get('cancel',40)).wallet.coins,100);
 check('cancel retains original work attempt count',(await row('cancel')).stats.launcherCompanionsV1.workStartsToday,1);
 await add('expires');const expiring=await start('expires');const expiredGet=await get('expires',181);
 check('disconnected challenge expires without payout',expiredGet.wallet.coins,100);
 check('expired challenge no longer occupies active slot',expiredGet.activeMinigame,null);
 check('expired finish cannot claim',(await cmd('expires','minigame.finish',ref(expiring.minigame),181)).error,'minigame_expired');
 await add('roomchange');const roomStart=await start('roomchange');const moved=(await row('roomchange')).stats;moved.launcherRoomV1.revision++;
 await db.query('UPDATE player_profiles SET stats=$1::jsonb WHERE secret=$2',[JSON.stringify(moved),'roomchange']);
 check('room edit invalidates live challenge',(await cmd('roomchange','minigame.finish',ref(roomStart.minigame),40)).error,'minigame_invalidated');
 check('room edit never awards coins',(await get('roomchange',40)).wallet.coins,100);
 await add('removed');const removed=await start('removed');const removedStats=(await row('removed')).stats;removedStats.launcherRoomV1.characters=[];
 await db.query('UPDATE player_profiles SET stats=$1::jsonb WHERE secret=$2',[JSON.stringify(removedStats),'removed']);
 check('unplaced actor invalidates session even without revision bump',(await cmd('removed','minigame.finish',ref(removed.minigame),40)).error,'minigame_invalidated');
 check('unplaced actor cannot start another game',(await start('removed')).error,'not_placed');
 await add('legacy-first');await S.startLauncherCharacterWork(pool,'legacy-first',id('luffy'),now(0),cap);
 check('interactive start respects existing legacy work',(await start('legacy-first')).error,'work_active');
 const together=await start('legacy-first','work',id('zoro'),1);const togetherDone=await play('legacy-first',together,1);
 check('different actor can play beside background job',togetherDone.response.wallet.coins,110);
 check('legacy job still pays once after interactive game',(await S.claimLauncherCharacterWork(pool,'legacy-first',id('luffy'),now(301),cap)).wallet.coins,120);
 check('follow-up life sync cannot double settle old job',(await get('legacy-first',302)).wallet.coins,120);
 await add('daily',stats(['luffy','zoro','nami','usopp']));
 for(const key of ['luffy','luffy','zoro','zoro','nami','nami']){const r=await start('daily','work',id(key),0);assert.equal(r.ok,true,JSON.stringify(r));await cmd('daily','minigame.cancel',ref(r.minigame),0);}
 check('global six attempts cannot be bypassed via new character',(await start('daily','work',id('usopp'))).error,'work_daily_limit');
 check('legacy API shares interactive global cap',(await S.startLauncherCharacterWork(pool,'daily',id('usopp'),now(0),cap)).error,'work_daily_limit');
 await add('peractor');for(let n=0;n<2;n++){const r=await start('peractor');await cmd('peractor','minigame.cancel',ref(r.minigame));}
 check('per-character two attempts enforced',(await start('peractor')).error,'work_daily_limit');
 check('next day resets shared start allowance',(await start('peractor','work',id('luffy'),86400)).ok,true);
 await add('training');const beforeTrain=await get('training');const training=await start('training','training');
 check('training starts with energy cost six',training.life.characters[id('luffy')].needs.energy,beforeTrain.life.characters[id('luffy')].needs.energy-6);
 check('training stages use four rounds',training.minigame.totalRounds,4);
 check('legacy train cannot overlap active training',(await cmd('training','character.interact',{itemId:id('luffy'),action:'train'})).error,'minigame_active');
 const trained=await play('training',training,0);
 check('training grants no wallet coins',trained.response.wallet.coins,100);
 check('training grants existing motivation effect',trained.response.minigame.result.workMotivation,5);
 check('training grants one affinity',(await row('training')).stats.launcherCompanionsV1.characters[id('luffy')].affinity,1);
 check('normal training shares ten minute cooldown',(await start('training','training',id('luffy'),30)).error,'interaction_cooldown');
 check('legacy train sees same cooldown',(await cmd('training','character.interact',{itemId:id('luffy'),action:'train'},30)).error,'interaction_cooldown');
 const beforePractice=await get('training',30),practice=await start('training','training',id('luffy'),30,{practice:true});
 check('practice permitted during reward cooldown',practice.ok,true);
 check('practice does not deduct energy',practice.life.characters[id('luffy')].needs.energy,beforePractice.life.characters[id('luffy')].needs.energy);
 const practiced=await play('training',practice,30);
 check('practice reports no reward',practiced.response.minigame.result,{passed:true,practice:true,canRetry:false,attempt:1,attemptsRemaining:0,coins:0,affinity:0,workMotivation:0,energyCost:0,correctRounds:4,totalRounds:4});
 check('practice cannot farm affinity',(await row('training')).stats.launcherCompanionsV1.characters[id('luffy')].affinity,1);
 await add('train-retry');const trainStart=await start('train-retry','training'),trainFail=await play('train-retry',trainStart,0,4);
 const energyBefore=(await get('train-retry',trainFail.t+1)).life.characters[id('luffy')].needs.energy,trainRetry=await cmd('train-retry','minigame.retry',ref(trainStart.minigame),trainFail.t+1);
 check('training retry does not charge energy twice',trainRetry.life.characters[id('luffy')].needs.energy,energyBefore);
 check('training retry preserves original cooldown',(await get('train-retry',trainFail.t+1)).life.characters[id('luffy')].lastInteractions.train,trainStart.serverNow);
 await add('full',stats(['luffy'],495));check('full wallet refuses paid work attempt',(await start('full')).error,'wallet_full');
 check('full wallet rejection consumes no attempt',(await row('full')).stats.launcherCompanionsV1.workStartsToday,0);
 await add('fills',stats(['luffy'],480));const fills=await start('fills');const fillStats=(await row('fills')).stats;fillStats.launcherWalletV1.coins=495;
 await db.query('UPDATE player_profiles SET stats=$1::jsonb WHERE secret=$2',[JSON.stringify(fillStats),'fills']);
 const held=await play('fills',fills);check('concurrent wallet fill retains successful result',held.response.error,'wallet_full');
 check('wallet-full pending claim does not exceed cap',held.response.wallet.coins,495);
 check('wallet-full pending claim keeps session ready',held.response.minigame.state,'ready');
 check('ready earned claim survives ordinary session timeout',(await get('fills',200)).activeMinigame.state,'ready');
 const spend=await S.changeLauncherItem(pool,'fills','bgm-op-01','buy',cap);check('pending reward can buy existing item',spend.ok,true);
 const heldClaim=await cmd('fills','minigame.finish',ref(fills.minigame),201);check('spending then claim grants only original ten coins',heldClaim.wallet.coins,495);
 check('held reward recorded only once',Number((await db.query('SELECT count(*) AS n FROM launcher_wallet_ledger WHERE user_id=$1',[(await row('fills')).user_id])).rows[0].n),1);
 await add('race');const raceSnap=await get('race');const pair=await Promise.all([cmd('race','minigame.start',{kind:'work',characterId:id('luffy')},0,{snapshot:raceSnap}),cmd('race','minigame.start',{kind:'work',characterId:id('zoro')},0,{snapshot:raceSnap})]);
 check('serialized concurrent starts create only one session',pair.filter(r=>r.ok).length,1);
 check('serialized concurrent starts consume only one allowance',(await row('race')).stats.launcherCompanionsV1.workStartsToday,1);
 const racePlayed=await play('race',pair.find(r=>r.ok));const raceSession=racePlayed.response.minigame,claimSnap=await get('race',30);
 const replays=await Promise.all([cmd('race','minigame.finish',ref(raceSession),30,{snapshot:claimSnap}),cmd('race','minigame.finish',ref(raceSession),30,{snapshot:claimSnap})]);
 check('concurrent repeated completions preserve balance',replays.map(r=>r.wallet.coins),[110,110]);
 check('concurrent repeated completions preserve one receipt',Number((await db.query('SELECT count(*) AS n FROM launcher_wallet_ledger WHERE user_id=$1',[(await row('race')).user_id])).rows[0].n),1);
 check('no new gameplay XP field introduced',JSON.stringify((await row('race')).stats).includes('"xp"'),false);
 const sources=['server/launcher-life-store.js','server/launcher-minigames.js','scripts/launcher_minigames_server_qa.js'];
 const report={schemaVersion:1,status:'PASS',checks:checks.length,results:checks,sourceHashes:Object.fromEntries(sources.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..',file))).digest('hex')])),limitations:['Isolated in-memory PGlite with serialized transaction adapter; not a production PostgreSQL concurrency or human play test.'],createdAt:new Date().toISOString()};
 const output=process.argv[2];if(output){fs.mkdirSync(path.dirname(path.resolve(output)),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');}
 console.log(JSON.stringify({status:'PASS',checks:checks.length,output:output||null}));
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;}).finally(()=>db.close());
