'use strict';
// Reports and actual visual observations must already exist; this binds their
// bytes and refuses to manufacture or overwrite acceptance evidence.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const gate=require('./validate_release'),history=require('./validate_historical');
function walk(root,directory,result=new Set()){const full=path.join(root,directory);if(!fs.existsSync(full))return result;for(const entry of fs.readdirSync(full,{withFileTypes:true})){assert(!entry.isSymbolicLink());const file=directory+'/'+entry.name;if(entry.isDirectory())walk(root,file,result);else if(entry.isFile())result.add(file);}return result;}
function freeze(root,options={}){
 root=path.resolve(root);const read=gate.reader(root,options),bind=file=>({path:file,sha256:history.sha256(read(file))});assert(options.scope,'Explicit release-scope JSON required');const input=JSON.parse(fs.readFileSync(options.scope)),scope=Array.isArray(input)?input:input.files;assert(Array.isArray(scope)&&scope.every(file=>typeof file==='string'));
 const legacy=history.validateHistorical(root),evidence=walk(root,gate.EVIDENCE_PREFIX.replace(/\/$/,''));if(options.staging)walk(options.staging,gate.EVIDENCE_PREFIX.replace(/\/$/,''),evidence);const qaSourceProofs={};
 for(const file of Object.values(gate.REPORTS)){const report=JSON.parse(read(gate.EVIDENCE_PREFIX+file)),sources=report.sourceSha256||report.sourceHashes;if(!sources)continue;for(const [source,digest]of Object.entries(sources)){const bytes=read(source);assert.equal(history.sha256(bytes),digest,'Freeze requires the exact tested source bytes: '+source);const proof={sha256:digest,normalizedSha256:history.normalized(bytes)};if(qaSourceProofs[source])assert.deepEqual(qaSourceProofs[source],proof);qaSourceProofs[source]=proof;}}
 const review={schema:'launcher-room-expansion-release/1',releaseVersion:'1.2.8',baseline:history.BASELINE,recordedAt:new Date().toISOString(),status:'PASS_WITH_NOTES',humanAcceptance:false,blockingIssues:[],method:'Existing immutable 1.2.7 and earlier gates are rerun through byte-bound historical overlays. Current server economy, real Chromium minigames and room renderer, all 32 GPT assets and independent visual observations are bound to the exact tested source and pixels.',limitations:['Automated PGlite and Chromium checks are not human play or physical-device acceptance.','Source/art approval alone does not prove installer publication or canonical deployment.'],runtimeHashNormalization:history.NORMALIZATION,runtime:Object.fromEntries(Object.keys(legacy.review.runtime).map(file=>[file,history.normalized(read(file))])),approvedRuntimeVariants:legacy.review.approvedRuntimeVariants,gateSources:Object.fromEntries(gate.GATE_FILES.map(file=>[file,history.normalized(read(file))])),historicalReview:bind(history.REVIEW),historicalOverlay:bind(history.MANIFEST),gameBaseline:bind(gate.EVIDENCE_PREFIX+'game-baseline.json'),art:bind(gate.ART_MANIFEST),releaseScope:[...new Set(scope)].sort(),qaSourceNormalization:history.NORMALIZATION,qaSourceProofs,evidence:[...evidence].sort().map(bind),...Object.fromEntries(Object.entries(gate.REPORTS).map(([key,file])=>[key,bind(gate.EVIDENCE_PREFIX+file)])),visualReview:bind(gate.EVIDENCE_PREFIX+'independent-visual-review.json')};
 if(evidence.has(gate.FORMAL_MERGE_PATH))review.formalAnnouncementMerge=bind(gate.FORMAL_MERGE_PATH);
 const result=gate.validateReview(root,review,legacy,options),output=path.join(options.staging||root,gate.REVIEW_PATH);assert(!fs.existsSync(output),'Review already exists; preserve it before an explicit new freeze');fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(review,null,2)+'\n',{flag:'wx'});return{status:'PASS',review:output,sha256:history.sha256(fs.readFileSync(output)),newAssets:result.newAssets,runtimeFiles:result.currentRuntimeFiles,serverChecks:result.serverChecks,clientChecks:result.functionalChecks,roomChecks:result.roomChecks};
}
module.exports={freeze};
if(require.main===module){const args=process.argv.slice(2),option=key=>{const index=args.indexOf(key);return index<0?undefined:args[index+1];};console.log(JSON.stringify(freeze(option('--root')||path.resolve(__dirname,'../../..'),{staging:option('--staging'),scope:option('--scope')})));}
