'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const history=require('./validate_historical'),previous=require('../presentation-v127/validate_release');
const REVIEW_PATH='docs/LAUNCHER_ROOM_EXPANSION_20260928.json',PREFIX='tools/launcher-room/expansion-v128/',EVIDENCE_PREFIX=PREFIX+'review-evidence/',ART_MANIFEST=PREFIX+'art-manifest.json';
const SCENES=['sunny-workshop','sunny-aquarium'],FURNITURE=['supply-rack','log-pose-desk','repair-cart','library-cart','medical-cart','den-den-desk'];
const EXPANSION_ASSETS=[...SCENES.map(key=>'scenes/'+key+'.webp'),...FURNITURE.map(key=>'furniture/'+key+'.webp'),...FURNITURE.flatMap(key=>[0,1,2,3].map(rotation=>'furniture_views/'+key+'/'+rotation+'.webp'))].map(file=>'public/images/launcher_room/'+file);
const GAME_FILES=['public/desktop/catalog-v2.json','public/desktop/catalog-v3.json','config/desktop-program-packages-v1.json'];
const GATE_FILES=[...['export_historical.js','validate_historical.js','validate_release.js','freeze_review.js'].map(file=>PREFIX+file),'scripts/desktop_launcher_package_qa.js'];
const REPORTS={serverQA:'server-qa.json',clientQA:'client/EXPANSION_CLIENT_QA.json',catalogQA:'catalog/CATALOG_QA.json',roomQA:'catalog/ROOM_ASSET_QA.json',wheelQA:'wheel/EXPANSION_WHEEL_QA.json',legacyClientQA:'legacy/MINIGAMES_CLIENT_QA.json',legacyServerQA:'existing-minigames.json',lifeQA:'life-regression.json'};
const ANNOUNCEMENTS_PATH='config/launcher-announcements-v1.json',FORMAL_MERGE_PATH=EVIDENCE_PREFIX+'formal-announcements-merge.json';
const {safe,sha256,normalized}=history;
function reader(root,options={}){return file=>{const staged=options.staging?safe(options.staging,file):null;return fs.readFileSync(staged&&fs.existsSync(staged)?staged:safe(root,file));};}
function bound(read,item){assert(item&&typeof item.path==='string');assert.match(item.sha256,/^[a-f0-9]{64}$/);const bytes=read(item.path);assert.equal(sha256(bytes),item.sha256,'Bound file changed: '+item.path);if(item.bytes!==undefined)assert.equal(bytes.length,item.bytes);return bytes;}
function checks(report){assert(report.status==='PASS'||report.ok===true,'QA is not successful');assert.equal(report.humanAcceptance??false,false);const result=Array.isArray(report.checks)?report.checks:report.results;assert(Array.isArray(result)&&result.length);assert(result.every(item=>item.status==='PASS'||item.pass===true),'QA contains a failed check');return result;}
function sourceBindings(read,report,proofs){const sources=report.sourceSha256||report.sourceHashes;assert(sources&&Object.keys(sources).length>=3,'QA needs actual source bindings');for(const [file,digest]of Object.entries(sources)){const proof=proofs[file];assert(proof,'Missing CRLF-only source proof: '+file);assert.equal(proof.sha256,digest);assert.equal(normalized(read(file)),proof.normalizedSha256,'QA source changed: '+file);}return Object.keys(sources);}
function assetsBound(read,report){assert(report.assetSha256&&Object.keys(report.assetSha256).length,'Browser must bind decoded assets');for(const [file,digest]of Object.entries(report.assetSha256))assert.equal(sha256(read(file)),digest,'Browser art changed: '+file);}
function validateFormalAnnouncementMerge(root,read,review){
 if(!review.formalAnnouncementMerge)return null;
 assert.equal(review.formalAnnouncementMerge.path,FORMAL_MERGE_PATH);const proof=JSON.parse(bound(read,review.formalAnnouncementMerge));assert.equal(proof.schema,'launcher-v128-formal-announcements-merge/1');assert.equal(path.resolve(proof.formalRoot).toLowerCase(),path.resolve(previous.FORMAL_ROOT).toLowerCase());assert.equal(proof.addedId,'launcher-1.2.8-room-expansion');assert.equal(proof.candidate.path,ANNOUNCEMENTS_PATH);assert.equal(typeof proof.candidate.text,'string');
 const candidateBytes=Buffer.from(proof.candidate.text,'utf8');assert.equal(sha256(candidateBytes),proof.candidate.sha256);assert.equal(normalized(candidateBytes),proof.candidate.normalizedSha256);assert.equal(proof.candidate.normalizedSha256,review.runtime[ANNOUNCEMENTS_PATH],'Formal exception must bind the unchanged candidate announcement');
 assert.equal(proof.before.path,EVIDENCE_PREFIX+'formal-announcements-before.json');assert.equal(proof.merged.path,EVIDENCE_PREFIX+'formal-announcements-merged.json');const before=JSON.parse(bound(read,proof.before)),mergedBytes=bound(read,proof.merged),merged=JSON.parse(mergedBytes),candidate=JSON.parse(candidateBytes);assert.equal(normalized(mergedBytes),proof.merged.normalizedSha256);
 const validate=require(path.join(root,'server/launcher-announcements.js')).validateConfig;for(const config of [candidate,before,merged])validate(config);
 const beforeIds=new Map(before.announcements.map(item=>[item.id,item])),candidateIds=new Map(candidate.announcements.map(item=>[item.id,item])),mergedIds=new Map(merged.announcements.map(item=>[item.id,item])),own=candidateIds.get(proof.addedId);assert(own&&own.scope==='launcher'&&own.requiredRelease?.version==='1.2.8');assert(!beforeIds.has(proof.addedId),'Before snapshot already contains this release');assert.equal(merged.revision,Math.max(before.revision,candidate.revision)+1);assert.equal(mergedIds.size,beforeIds.size+1);for(const [id,item]of beforeIds)assert.deepEqual(mergedIds.get(id),item,'Concurrent formal notice changed: '+id);for(const [id,item]of candidateIds){assert.deepEqual(mergedIds.get(id),item,'Candidate notice changed in formal merge: '+id);assert(id===proof.addedId||beforeIds.has(id),'Formal merge adds an unrelated candidate notice');}assert.deepEqual(mergedIds.get(proof.addedId),own);
 const additional=[...beforeIds.keys()].filter(id=>!candidateIds.has(id)).sort();assert.deepEqual([...proof.retainedAdditionalIds].sort(),additional);const original=JSON.parse(history.git(root,['cat-file','blob',history.BASELINE+':'+ANNOUNCEMENTS_PATH]));assert.deepEqual([...candidateIds.keys()].sort(),[...original.announcements.map(item=>item.id),proof.addedId].sort(),'Candidate must not publish concurrent game work');for(const item of original.announcements)assert.deepEqual(candidateIds.get(item.id),item);
 for(const item of [review.formalAnnouncementMerge,proof.before,proof.merged]){assert(review.evidence.some(entry=>entry.path===item.path&&entry.sha256===item.sha256),'Formal merge evidence is not frozen');assert(review.releaseScope.includes(item.path),'Formal merge evidence is missing from release scope');}
 return proof;
}
function validateRuntime(root,read,review,formalMerge){
 const formal=path.resolve(root).toLowerCase()===path.resolve(previous.FORMAL_ROOT).toLowerCase();for(const [file,digest]of Object.entries(review.runtime)){const allowed=formal&&formalMerge&&file===ANNOUNCEMENTS_PATH?[formalMerge.merged.normalizedSha256]:[digest,...(review.approvedRuntimeVariants[file]||[]).map(item=>item.normalizedSha256)];assert(allowed.includes(normalized(read(file))),'Reviewed runtime changed: '+file);}
}
function validateArt(read,review){
 assert.equal(review.art.path,ART_MANIFEST);const manifest=JSON.parse(bound(read,review.art));assert.equal(manifest.schema,'launcher-room-expansion-gpt-art/1');assert.equal(manifest.tool,'built-in image_gen');assert.equal(manifest.humanAcceptance,false);
 assert.deepEqual(manifest.sources.map(item=>item.key).sort(),[...SCENES,...FURNITURE].sort());assert.deepEqual(manifest.assets.map(item=>item.path).sort(),[...EXPANSION_ASSETS].sort());
 for(const source of manifest.sources){assert.equal(source.kind,SCENES.includes(source.key)?'scene':'furniture');for(const key of ['image','prompt','receipt']){assert(source[key].path.startsWith(PREFIX+'sources/'+source.key+'/'));bound(read,source[key]);}const receipt=JSON.parse(read(source.receipt.path));assert.equal(receipt.tool,'image_gen.imagegen');assert.equal(receipt.key,source.key);assert(read(source.prompt.path).length>100);}
 for(const item of manifest.assets){const bytes=bound(read,item);assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.equal(bytes.toString('ascii',8,12),'WEBP');assert(item.bytes>1000);assert(manifest.sources.some(source=>source.key===item.source));
  if(item.path.includes('/scenes/')){assert.equal(item.width,1600);assert.equal(item.height,900);assert.equal(item.alpha,false);assert(SCENES.includes(item.source));}
  else{assert.equal(item.width,384);assert.equal(item.height,384);assert.equal(item.alpha,true);assert(FURNITURE.includes(item.source));if(item.path.includes('/furniture_views/')){assert.equal(item.rotation,Number(path.posix.basename(item.path,'.webp')));assert(Number.isFinite(item.uniformScale)&&item.uniformScale>0);assert.deepEqual(item.groundRoot,[192,372]);}else assert.equal(item.thumbnail,true);}
 }
 for(const key of FURNITURE){const views=manifest.assets.filter(item=>item.source===key&&item.path.includes('/furniture_views/'));assert.equal(views.length,4);assert.equal(new Set(views.map(item=>item.uniformScale)).size,1,'Furniture directions must share one scale');assert.equal(new Set(views.map(item=>item.sha256)).size,4,'Four furniture directions need distinct pixels');}
 return manifest;
}
function validateNotes(root,read){
 const config=JSON.parse(read('config/launcher-announcements-v1.json'));require(path.join(root,'server/launcher-announcements.js')).validateConfig(config);
 const old=JSON.parse(history.git(root,['cat-file','blob',history.BASELINE+':config/launcher-announcements-v1.json']));assert.equal(config.schemaVersion,1);assert(config.revision>old.revision);const byId=new Map(config.announcements.map(item=>[item.id,item]));assert.equal(byId.size,config.announcements.length);
 for(const item of old.announcements)if(item.status==='published')assert.deepEqual(byId.get(item.id),item,'Published announcement changed: '+item.id);
 const current=config.announcements.filter(item=>item.status==='published'&&item.scope==='launcher'&&item.category==='update'&&item.requiredRelease?.kind==='launcher'&&item.requiredRelease.version==='1.2.8');assert.equal(current.length,1,'One release-gated launcher expansion announcement required');const note=current[0];assert(note.title?.length>=4&&note.summary?.length>=12&&Number.isFinite(Date.parse(note.publishedAt)));assert(Array.isArray(note.body)&&note.body.every(line=>typeof line==='string'&&line.length>=8));const text=[note.title,note.summary,...note.body].join(' ');for(const word of ['料理','維修','導航','金幣','家具','場景'])assert(text.includes(word),'Expansion note omits '+word);
 assert(!config.announcements.some(item=>item.status==='published'&&['room-character-sabo','room-character-law','room-character-hancock'].includes(item.requiresCharacterId)));return{entries:config.announcements.length,currentNotes:current.length};
}
function validateGames(root,read,review){
 const snapshot=JSON.parse(bound(read,review.gameBaseline));assert.equal(snapshot.schema,'launcher-v128-game-baseline/1');assert.equal(path.resolve(snapshot.authorityRoot).toLowerCase(),path.resolve(previous.FORMAL_ROOT).toLowerCase());assert(Number.isFinite(Date.parse(snapshot.capturedAt)));assert.deepEqual(snapshot.files.map(item=>item.path).sort(),[...GAME_FILES].sort());
 assert(Array.isArray(review.releaseScope)&&review.releaseScope.length>0);assert(!review.releaseScope.some(file=>GAME_FILES.includes(file)||/^public\/(?:board|card|chess)[_/.]/.test(file)||/^public\/js\/(?:board|card|chess)_/.test(file)),'Launcher expansion may not publish unrelated game edits');
 const formal=path.resolve(root).toLowerCase()===path.resolve(previous.FORMAL_ROOT).toLowerCase();for(const item of snapshot.files){assert.match(item.sha256,/^[a-f0-9]{64}$/);if(formal)assert.equal(sha256(read(item.path)),item.sha256,'Formal game catalog changed');else assert.equal(normalized(read(item.path)),normalized(history.git(root,['cat-file','blob',history.BASELINE+':'+item.path])),'Candidate game catalog changed');}
 return{gameCatalogsWritten:false,baseline:history.BASELINE,formalSnapshotSha256:review.gameBaseline.sha256};
}
function validateReview(root,review,legacy,options={}){
 const read=reader(root,options),json=file=>JSON.parse(read(file));assert.equal(review.schema,'launcher-room-expansion-release/1');assert.equal(review.releaseVersion,'1.2.8');assert.equal(review.baseline,history.BASELINE);assert.equal(review.status,'PASS_WITH_NOTES');assert.equal(review.humanAcceptance,false);assert.deepEqual(review.blockingIssues,[]);assert.equal(review.runtimeHashNormalization,history.NORMALIZATION);
 assert.equal(review.historicalReview.path,history.REVIEW);assert.equal(review.historicalReview.sha256,history.REVIEW_SHA);bound(read,review.historicalReview);assert.equal(review.historicalOverlay.path,history.MANIFEST);assert.equal(sha256(bound(read,review.historicalOverlay)),legacy.v127OverlaySha256);
 assert.deepEqual(Object.keys(review.runtime).sort(),Object.keys(legacy.review.runtime).sort());assert.deepEqual(review.approvedRuntimeVariants,legacy.review.approvedRuntimeVariants);const formalMerge=validateFormalAnnouncementMerge(root,read,review);validateRuntime(root,read,review,formalMerge);
 assert.deepEqual(Object.keys(review.gateSources).sort(),[...GATE_FILES].sort());for(const [file,digest]of Object.entries(review.gateSources))assert.equal(normalized(read(file)),digest,'Release gate changed since review: '+file);
 const pkg=json('desktop/package.json'),lock=json('desktop/package-lock.json');assert.equal(pkg.version,'1.2.8');assert.equal(lock.version,pkg.version);assert.equal(lock.packages[''].version,pkg.version);
 assert.deepEqual(json('config/launcher-crew-release-v1.json'),{schemaVersion:1,rosterRevision:2,characters:{ace:true,sabo:false,law:false,hancock:false}},'Locked characters must remain unavailable');
 const announcements=validateNotes(root,read),catalogs=validateGames(root,read,review),art=validateArt(read,review),evidence=new Map();for(const item of review.evidence){assert(item.path.startsWith(EVIDENCE_PREFIX)&&!evidence.has(item.path));bound(read,item);evidence.set(item.path,item);}
 const reports={};for(const [key,file]of Object.entries(REPORTS)){assert.equal(review[key].path,EVIDENCE_PREFIX+file);assert.equal(evidence.get(review[key].path)?.sha256,review[key].sha256);const report=JSON.parse(bound(read,review[key]));reports[key]={report,checks:checks(report)};}
 assert.equal(review.qaSourceNormalization,history.NORMALIZATION);for(const key of ['serverQA','clientQA','catalogQA','roomQA','wheelQA','legacyClientQA','legacyServerQA'])sourceBindings(read,reports[key].report,review.qaSourceProofs);
 const server=reports.serverQA;assert(server.checks.length>=128);for(const job of ['cooking','repair','navigation'])assert(server.report.coverage[job].generatedRounds>=256&&server.report.coverage[job].distinctLayouts>1);assert(Object.hasOwn(server.report.sourceHashes,'scripts/launcher_work_variants_server_qa.js'));
 const client=reports.clientQA;assert.equal(client.report.schema,'launcher-expansion-client-qa/1');assert(client.checks.length>=11);for(const job of ['cooking','repair','navigation'])assert(client.checks.some(item=>item.name===job+'-eight-real-rounds-keyboard-mouse-undo-and-ten-shop-coins'));assert(client.checks.some(item=>item.name==='three-jobs-share-one-wallet-and-daily-ledger'));assert(Object.hasOwn(client.report.sourceSha256,'scripts/launcher_room_expansion_client_qa.js'));assert(client.report.limitations.some(line=>/Real service/.test(line)));assetsBound(read,client.report);
 const catalog=reports.catalogQA;assert.equal(catalog.report.schema,'launcher-room-expansion-catalog-qa/1');assert(catalog.checks.length>=10);assert.deepEqual(catalog.report.products.map(item=>item.id).sort(),[...SCENES.map(key=>'room-scene-'+key),...FURNITURE.map(key=>'room-furniture-'+key)].sort());assert(Object.hasOwn(catalog.report.sourceSha256,'scripts/launcher_room_expansion_catalog_qa.js'));
 const room=reports.roomQA;assert.equal(room.report.schema,'launcher-room-expansion-renderer-qa/1');assert(room.checks.length>=8);assert.equal(room.report.requireAssets,true);assert.deepEqual(room.report.errors,[]);assert.deepEqual(room.report.missing,[]);assert(Object.hasOwn(room.report.sourceSha256,'scripts/launcher_room_expansion_browser_qa.js'));assetsBound(read,room.report);for(const file of EXPANSION_ASSETS)assert.equal(room.report.assetSha256[file],sha256(read(file)),'Room QA must decode every new view');
 const wheel=reports.wheelQA;assert.equal(wheel.report.schema,'room-wheel-expansion-integration/1');assert(wheel.checks.length>=7);assert(Object.hasOwn(wheel.report.sourceSha256,'scripts/launcher_room_expansion_wheel_qa.js'));assetsBound(read,wheel.report);
 assert(reports.legacyClientQA.checks.length>=12);assert(reports.legacyServerQA.checks.length>=96);assert(reports.lifeQA.checks.length>=160);
 for(const key of ['clientQA','roomQA','wheelQA']){const report=reports[key].report;assert(report.captures.length>=4);for(const capture of report.captures){const name=capture.path||capture.file,file=name.startsWith(EVIDENCE_PREFIX)?name:path.posix.join(path.posix.dirname(review[key].path),name);assert.equal(evidence.get(file)?.sha256,capture.sha256,'Current browser pixels are not bound: '+file);}}
 assert(client.report.captures.some(item=>item.viewport?.width===390)&&client.report.captures.some(item=>item.viewport?.width>=1280));for(const scene of SCENES)for(const width of [1366,390])assert(room.report.captures.some(item=>(item.file||item.path)===scene+'-'+width+'.png'));
 const visual=JSON.parse(bound(read,review.visualReview));assert.equal(evidence.get(review.visualReview.path)?.sha256,review.visualReview.sha256);assert(['PASS','PASS_WITH_NOTES'].includes(visual.status));assert.equal(visual.humanAcceptance,false);assert.deepEqual(visual.blockingIssues,[]);assert(typeof visual.method==='string'&&visual.method.length>20);assert(Array.isArray(visual.images)&&visual.images.length>=6);assert.deepEqual([...new Set(visual.images.map(item=>item.subject))].sort(),['jobs','rooms']);for(const item of visual.images)assert.equal(evidence.get(item.path)?.sha256,item.sha256,'Visual review is not of the tested pixels');
 const newItems=art.assets.map(item=>({asset:item.path,assetSha256:item.sha256,assetBytes:item.bytes}));return{...legacy,complete:true,review,historicalOnly:false,historicalV127:true,announcements,catalogs,serverChecks:server.checks.length,functionalChecks:client.checks.length,interactionChecks:wheel.checks.length,catalogChecks:catalog.checks.length,roomChecks:room.checks.length,newAssets:newItems.length,newArt:{...legacy.newArt,manifest:{items:[...legacy.newArt.manifest.items,...newItems]},expansion:art},currentRuntimeFiles:Object.keys(review.runtime).length,activeCharacters:11};
}
function validate(root,options={}){const read=reader(root,options);return validateReview(root,JSON.parse(read(REVIEW_PATH)),history.validateHistorical(root),options);}
module.exports={validate,validateReview,validateArt,validateNotes,validateGames,validateFormalAnnouncementMerge,validateRuntime,reader,REVIEW_PATH,PREFIX,EVIDENCE_PREFIX,ART_MANIFEST,SCENES,FURNITURE,EXPANSION_ASSETS,GAME_FILES,GATE_FILES,REPORTS,FORMAL_MERGE_PATH,MINIGAME_ASSETS:previous.MINIGAME_ASSETS,ROBIN_ASSETS:previous.ROBIN_ASSETS};
if(require.main===module){const args=process.argv.slice(2),option=key=>{const index=args.indexOf(key);return index<0?undefined:args[index+1];};const result=validate(option('--root')||path.resolve(__dirname,'../../..'),{staging:option('--staging')});console.log(JSON.stringify({complete:true,version:result.review.releaseVersion,newAssets:result.newAssets,serverChecks:result.serverChecks,clientChecks:result.functionalChecks,roomChecks:result.roomChecks,catalogChecks:result.catalogChecks,historicalV127:result.historicalV127,humanAcceptance:false}));}
