"use strict";
// Rebuild the authored presentation registry; this never reads or writes saves.
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const input = JSON.parse(fs.readFileSync(path.join(__dirname, "data/board_move_fx_v1.json"), "utf8").replace(/^\uFEFF/, ""));
const catalog = { version: 1, assetVersion: "20260921-v1", families: input.families, moves: input.moves, variants: input.variants, aliases: input.aliases };
const missing = [];
for (const [id, family] of Object.entries(catalog.families)) {
  if (!fs.existsSync(path.join(root, "public", family.sheet))) missing.push({ type: "image", id, file: family.sheet });
}
const profiles = [...Object.entries(catalog.moves), ...catalog.variants.map((v) => [v.moveId, v.profile])];
for (const [id, move] of profiles) {
  if (!catalog.families[move.art]) throw Error(`Unknown image family: ${id}/${move.art}`);
  for (const phase of ["sound", "castSound"]) {
    const file = move[phase];
    if (file && (!/^audio\/board_game\/move-fx\/v1\/[\w.-]+\.ogg$/.test(file) || !fs.existsSync(path.join(root, "public", file)))) missing.push({ type: phase, id, file });
  }
}
if (process.argv.includes("--check-assets") && missing.length) throw Error(JSON.stringify({ missing }, null, 2));
fs.writeFileSync(path.join(root, "public/js/board_move_fx_catalog.js"), "// Generated by scripts/build_board_move_fx_catalog.js from the authored per-move registry.\nwindow.BoardMoveFxCatalog = " + JSON.stringify(catalog) + ";\n");
fs.writeFileSync(path.join(root, "public/js/board_move_fx_preview_data.js"), "// Preview only; not loaded by the game.\nwindow.BoardMoveFxPreviewData = " + JSON.stringify(input.previewEntries) + ";\n");
console.log(JSON.stringify({ families: Object.keys(catalog.families).length, moves: Object.keys(catalog.moves).length, variants: catalog.variants.length, aliases: Object.keys(catalog.aliases).length, previewEntries: input.previewEntries.length, missingFiles: missing.length }));
