"""Generate compact, reproducible alpha hit masks for the launcher room.

The renderer ships these masks inside an existing, signed content-update JS file.
Each payload starts with its frame count. Every frame has 64 rows, encoded as a
count byte followed by [inclusive start, exclusive end] byte pairs for every
opaque run. Alpha is BOX downsampled to 64x64 before thresholding at 16.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "public" / "images" / "launcher_room"
OUTPUT = ROOT / "desktop" / "launcher-room-motion-data.js"
DIRECTORIES = (
    "furniture_views",
    "furniture",
    "chibi",
    "portrait_v2",
    "portrait_v3",
    "portrait_v4",
    "motion_v3",
    "motion_v4",
    "motion_v5",
    "acting_v3",
    "acting_v4",
    "acting_v5",
    "life_v1",
    "life_hd_v2",
    "life_hd_v3",
    "action_frames",
    "frames",
    "robin_v2",
    "reserved_v1",
    "reserved_v2",
    "reserved_v3",
)
SIZE = 64
ALPHA_THRESHOLD = 16
BEGIN = "// BEGIN GENERATED ROOM ALPHA HIT MASKS v1"
END = "// END GENERATED ROOM ALPHA HIT MASKS v1"


def frame_count(relative: Path) -> int:
    parts = relative.parts
    if any(part in parts for part in ("acting_v3", "acting_v4", "acting_v5", "acting")):
        return 8
    if any(part in parts for part in ("motion_v3", "motion_v4", "motion_v5", "walk", "life", "life_v1", "life_hd_v2", "life_hd_v3")):
        return 4
    return 1


def runs_for_alpha(image: Image.Image) -> bytearray:
    small = image.getchannel("A").resize((SIZE, SIZE), Image.Resampling.BOX)
    values = small.tobytes()
    output = bytearray()
    for y in range(SIZE):
        row = values[y * SIZE : (y + 1) * SIZE]
        spans: list[tuple[int, int]] = []
        x = 0
        while x < SIZE:
            if row[x] < ALPHA_THRESHOLD:
                x += 1
                continue
            start = x
            x += 1
            while x < SIZE and row[x] >= ALPHA_THRESHOLD:
                x += 1
            spans.append((start, x))
        assert len(spans) <= 32
        output.append(len(spans))
        for start, end in spans:
            output.extend((start, end))
    return output


def encode_image(path: Path, count: int) -> str:
    with Image.open(path) as image:
        image = image.convert("RGBA")
        if count > 1 and image.width != count * image.height:
            raise ValueError(f"Atlas geometry mismatch: {path}: {image.size}, expected {count} square frames")
        payload = bytearray((count,))
        for frame in range(count):
            if count == 1:
                tile = image
            else:
                left = frame * image.height
                tile = image.crop((left, 0, left + image.height, image.height))
            payload.extend(runs_for_alpha(tile))
    return base64.b64encode(payload).decode("ascii")


def render_block() -> tuple[str, int, str]:
    files = sorted(
        (path for directory in DIRECTORIES for path in (ASSETS / directory).rglob("*.webp")),
        key=lambda path: path.relative_to(ASSETS).as_posix(),
    )
    if not files:
        raise RuntimeError(f"No room images found under {ASSETS}")
    source_hashes: list[str] = []
    encoded: dict[str, str] = {}
    for path in files:
        relative = path.relative_to(ASSETS)
        key = relative.as_posix()
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        source_hashes.append(f"{key}\0{digest}\n")
        encoded[key] = encode_image(path, frame_count(relative))
    aggregate = hashlib.sha256("".join(source_hashes).encode("utf-8")).hexdigest()
    block = (
        f"{BEGIN}\n"
        f"// Source files: {len(files)}; SHA-256 of sorted path\\0sha256\\n records: {aggregate}\n"
        f"// Generated by scripts/generate_launcher_room_hit_masks.py; edit sources and regenerate.\n"
        "if(typeof window==='object') window.OnePieceRoomAlphaMasks=Object.freeze({"
        f"size:{SIZE},assets:Object.freeze({json.dumps(encoded, ensure_ascii=True, separators=(',', ':'))})"
        "});\n"
        f"{END}\n"
    )
    return block, len(files), aggregate


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated block is current without writing")
    args = parser.parse_args()
    block, count, aggregate = render_block()
    original = OUTPUT.read_bytes()
    newline = b"\r\n" if b"\r\n" in original else b"\n"
    replacement = block.replace("\n", newline.decode("ascii")).encode("utf-8")
    begin = original.find(BEGIN.encode("ascii"))
    end = original.find(END.encode("ascii"))
    if (begin >= 0) != (end >= 0):
        raise RuntimeError("Incomplete generated mask block; preserve source and repair markers")
    if begin >= 0:
        after = end + len(END)
        if original[after : after + len(newline)] == newline:
            after += len(newline)
        result = original[:begin] + replacement + original[after:]
    else:
        result = original + (b"" if original.endswith(newline) else newline) + newline + replacement
    if args.check:
        if result != original:
            raise SystemExit("Room alpha masks are stale; run scripts/generate_launcher_room_hit_masks.py")
    else:
        OUTPUT.write_bytes(result)
    print(f"room alpha masks: {count} assets; sources SHA-256 {aggregate}; {len(replacement)} generated bytes")


if __name__ == "__main__":
    main()
