'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),D=require('../desktop/launcher-room-dialogue'),A=require('../desktop/launcher-life-actions');
const content=require('../tools/launcher-room/dialogue-v47/integrated-v2.json'),out='D:/Codex_QA/launcher-fishing-r47/dialogue';fs.mkdirSync(out,{recursive:true});const checks=[];const pass=(name,v)=>{assert.ok(v,name);checks.push(name);};
const vm=require('vm'),cp=require('child_process'),root=path.resolve(__dirname,'..'),baseline={module:{exports:{}},require:()=>require('../desktop/launcher-reserved-crew')};vm.runInNewContext(cp.execFileSync('git',['show','HEAD:desktop/launcher-room-dialogue.js'],{cwd:root,encoding:'utf8'}),baseline);const old=baseline.module.exports;
for(const a of D.KEYS){for(const kind of ['chat','work','bond','rest','claim'])for(let n=0;n<5;n++)pass('legacy '+a+' '+kind+' '+n,JSON.stringify(D.interactionBeat(a,kind,n))===JSON.stringify(old.interactionBeat(a,kind,n)));for(const b of D.KEYS)if(a<b)for(let n=0;n<3;n++)pass('legacy scene '+a+'/'+b+' '+n,JSON.stringify(D.scene(a,b,n,{daypart:'dusk',weather:'rain'}))===JSON.stringify(old.scene(a,b,n,{daypart:'dusk',weather:'rain'})));}
const keys=[...new Set(content.rows.map(r=>r.key))],base={expansionEnabled:true,isOwner:true,ownedKeys:keys,releasedKeys:keys,presentKeys:keys,readyKeys:keys,stationaryKeys:keys,sceneKey:'crew-cabin',transitionIds:{daypart:1,weather:1,season:1},availableFurnitureKeys:[],routeConfirmed:true,forgeReady:true,activityPhase:'performing',liveClip:true};
const context=row=>{const c={...base,event:row.scene,actorKey:row.key||row.pair[0],furnitureKey:row.furniture,availableFurnitureKeys:row.furniture?[row.furniture]:[],resultKey:row.id,confirmedResult:['fish_win','fish_loss','rare_fish'].includes(row.scene)};const when={morning:['daypart','dawn'],dusk:['daypart','dusk'],night:['daypart','night'],rain:['weather','rain'],snow:['weather','snow'],thunder:['weather','storm'],spring:['season','spring'],summer:['season','summer'],autumn:['season','autumn'],winter:['season','winter']};if(when[row.scene])c[when[row.scene][0]]=when[row.scene][1];c.activity={work:'Work',meal:'Eat',train:'Train'}[row.scene];return c;};
for(const row of content.rows){D.resetExpansion();const c=context(row),beat=D.expansionBeat(row.key,row.scene,0,c);pass(row.id+' precise trigger',beat?.id===row.id);pass(row.id+' registered full-body clip',row.mode==='life'?A.supported(row.key,row.pose):D.POSES.includes(row.pose));pass(row.id+' duplicate prevented',D.expansionBeat(row.key,row.scene,0,c)===null);D.resetExpansion();pass(row.id+' visitor rejected',D.expansionBeat(row.key,row.scene,0,{...c,isOwner:false})===null);pass(row.id+' missing actor rejected',D.expansionBeat(row.key,row.scene,0,{...c,presentKeys:[]})===null);}
for(const row of content.pairs){D.resetExpansion();const c=context(row);pass(row.id+' exact pair and ordered turns',D.expansionScene(...row.pair,0,c)?.id===row.id);const reversed=D.expansionScene(row.pair[1],row.pair[0],0,c);pass(row.id+' encounter reversal preserves speakers',JSON.stringify(reversed?.turns)===JSON.stringify(row.turns));pass(row.id+' absent listener rejected',D.expansionScene(...row.pair,0,{...c,presentKeys:[row.pair[0]]})===null);D.commitExpansion(row.id,c);pass(row.id+' pair cooldown prevents repeat',D.expansionScene(...row.pair,0,c)===null);}
D.resetExpansion();pass('unknown environment skips',D.expansionBeat('luffy','rain',0,{...base})===null);pass('outdoor rain is not an indoor statement',D.expansionBeat('luffy','rain',0,{...base,weather:'rain',sceneKey:'sunny-deck'})===null);pass('fake local catch preview rejected',D.expansionBeat('luffy','fish_win',0,{...base,event:'fish_win',actorKey:'luffy',resultKey:'preview'})===null);pass('work talk cannot create a work clip',D.expansionBeat('luffy','work',0,{...base,activity:'Work',activityPhase:'approach',liveClip:false})===null);
pass('handoffs excluded',content.rows.every(r=>r.scene!=='fish_handoff')&&content.pairs.every(r=>r.scene!=='fish_handoff'));pass('original quotes not fabricated',content.verifiedOriginalQuotes===0&&content.rows.every(r=>r.classification==='game_original'));pass('no staged action is loaded',!JSON.stringify(content).includes('signature_daily')&&!JSON.stringify(content).includes('offer_item')&&!JSON.stringify(content).includes('inspect_rod'));
fs.writeFileSync(path.join(out,'selection-report.json'),JSON.stringify({status:'PASS',checks:checks.length,solo:273,pairs:29,turns:87,limits:'Selector/guard and registry proof, not pixel-level validation of 39 staged actions'},null,2));console.log('PASS '+checks.length+' dialogue selection checks');
