'use strict';
// Production HTML and room wheel, actual service functions, isolated SQL only.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=process.env.LAUNCHER_MINIGAMES_SOURCE_ROOT||path.resolve(__dirname,'..'),overlay=process.env.LAUNCHER_MINIGAMES_OVERLAY||root;
const out=path.join(overlay,'tools/launcher-room/presentation-v127/review-evidence/minigames-client');fs.mkdirSync(out,{recursive:true});
const scratch=path.join(overlay,'tools/launcher-room/presentation-v127/browser-temp');fs.mkdirSync(scratch,{recursive:true});process.env.TEMP=scratch;process.env.TMP=scratch;
const runtimeBase=path.join(process.env.LOCALAPPDATA,'OpenAI/Codex/runtimes/cua_node'),runtime=process.env.BOARD_QA_PLAYWRIGHT||fs.readdirSync(runtimeBase).map(name=>path.join(runtimeBase,name,'bin/node_modules/playwright')).find(file=>fs.existsSync(file));
const {chromium}=require(runtime),{PGlite}=require(process.env.BOARD_QA_PGLITE||'D:/Codex_QA/draw-result-art-20260922/deps/node_modules/@electric-sql/pglite');
const B=require(path.join(root,'server/launcher-life-store')),S=require(path.join(root,'server/launcher-profile-shop')),db=new PGlite(),cap={crewContentRevision:1};
const source=file=>fs.existsSync(path.join(overlay,file))?path.join(overlay,file):path.join(root,file),sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const sources=['desktop/launcher.html','desktop/launcher-room-minigames.js','desktop/launcher-room-minigames.css','desktop/launcher-life-room.js','desktop/launcher-room.js','desktop/launcher-room-motion.js','desktop/launcher-life-actions.js','desktop/launcher-profile-shop.js','scripts/launcher_minigames_room_wheel_qa.js','server/launcher-life-store.js','server/launcher-minigames.js'];
const bindings=()=>Object.fromEntries(sources.map(file=>[file,sha(fs.readFileSync(source(file)))]));
let tail=Promise.resolve(),server,browser,page,context;const checks=[],captures=[],errors=[],commands=[],requested=[],missing=[];
const pool={query:(...args)=>db.query(...args),async connect(){const previous=tail;let release;tail=new Promise(resolve=>release=resolve);await previous;return{query:(...args)=>db.query(...args),release};}};
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
function fixture(){
 window.__LAUNCHER_ROOM_QA__=true;
 const state={authenticated:true,profile:{userId:1,name:'羅賓基地整合測試',avatar:8,needsDisplayName:false},cacheRoot:'D:\\Fixture',freeBytes:20e9,preferences:{minimizeToTrayOnGameLaunch:false,gameDisplayMode:'borderless'},games:Object.fromEntries(['card','board','chess'].map(id=>[id,{status:'installed',hasInstalled:true}]))};
 window.onePieceDesktop={getState:async()=>state,onState(){},onSocialState(){},onLauncherUpdate(){},onProgress(){},onSessionKicked(){},getSocialState:async()=>({ok:true,state:{userId:1,ready:true,friends:[],requestsIn:[],requestsOut:[],unread:{},conversations:{}}}),socialRequest:async()=>({ok:true}),getLauncherUpdateState:async()=>({ok:true,state:{status:'current',currentVersion:'1.2.7'}}),getLauncherAnnouncements:async()=>({ok:true,announcements:[],unreadCount:0,total:0}),getLauncherProfile:id=>__roomService('profile',id),getLauncherShop:()=>__roomService('shop'),getLauncherLife:()=>__roomService('life'),commandLauncherLife:command=>__roomService('command',command),getLauncherCharacter:id=>__roomService('character',id),getLauncherComments:async()=>({ok:true,comments:[]})};
}
async function capture(name){const file=name+'.png';await page.screenshot({path:path.join(out,file)});captures.push({path:file,sha256:sha(fs.readFileSync(path.join(out,file))),viewport:page.viewportSize()});}
async function chooseRobin(){await page.locator('#roomStage').scrollIntoViewIfNeeded();const actor=page.locator('#roomCharacters [data-room-key="c:room-character-robin"]');const box=await actor.boundingBox();assert(box);await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await page.waitForFunction(()=>!document.getElementById('roomCompanionPanel').hidden&&document.getElementById('roomLifeWork')&&!document.getElementById('roomLifeWork').disabled);}
async function wheelAction(id){await page.locator('#roomCompanionWheel').focus();for(let i=0;i<6&&await page.locator('#roomCompanionWheel').getAttribute('data-selected-action')!==id;i++){await page.keyboard.press('ArrowDown');await page.waitForTimeout(110);}assert.equal(await page.locator('#roomCompanionWheel').getAttribute('data-selected-action'),id);await page.keyboard.press('Enter');await page.waitForFunction(()=>!document.getElementById('roomMinigameOverlay')?.hidden);}
async function closeIntro(){await page.getByRole('button',{name:'結束並關閉挑戰'}).click();await page.waitForFunction(()=>document.getElementById('roomMinigameOverlay').hidden);}
async function cancelGame(){await page.getByRole('button',{name:'結束並關閉挑戰'}).click();await page.getByRole('button',{name:'結束並回房間'}).click();await page.waitForFunction(()=>document.getElementById('roomMinigameOverlay').hidden);}
async function main(){
 const before=bindings();await db.exec('CREATE TABLE player_profiles(user_id SERIAL PRIMARY KEY,secret TEXT UNIQUE NOT NULL,name TEXT,avatar TEXT,stats JSONB,updated_at TIMESTAMPTZ DEFAULT now())');await db.query('INSERT INTO player_profiles(secret,name,avatar,stats) VALUES($1,$2,$3,$4::jsonb)',['wheel-owner','羅賓基地整合測試','8',JSON.stringify({client:{totals:{coins:73}},launcherWalletV1:{coins:100,lastGrantDay:new Date().toISOString().slice(0,10)},launcherOwnedV1:{items:['room-character-robin']},launcherRoomV1:{revision:1,sceneId:'room-scene-default',capacityVersion:2,placements:[],characters:[{itemId:'room-character-robin',x:480,y:440}]}})]);await B.getLauncherLife(pool,'wheel-owner',new Date(),cap);
 server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\//,'')||'launcher.html',target=source('desktop/'+rel);if(rel.includes('..')||!fs.existsSync(target)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(target));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browsers=path.join(process.env.LOCALAPPDATA,'ms-playwright'),executablePath=fs.readdirSync(browsers).filter(n=>/^chromium-/.test(n)).sort().reverse().map(n=>path.join(browsers,n,'chrome-win64/chrome.exe')).find(file=>fs.existsSync(file));browser=await chromium.launch({headless:true,executablePath,args:['--disable-gpu-shader-disk-cache']});context=await browser.newContext({viewport:{width:1280,height:900}});await context.addInitScript(fixture);
 await context.exposeFunction('__roomService',async(type,value)=>{if(type==='profile')return S.getLauncherProfile(pool,'wheel-owner',Number(value)||0,null,cap);if(type==='shop')return S.getLauncherShop(pool,'wheel-owner',false,cap);if(type==='life')return B.getLauncherLife(pool,'wheel-owner',new Date(),cap);if(type==='character')return S.getLauncherCharacter(pool,'wheel-owner',value,new Date(),cap);if(type==='command'){const response=await B.commandLauncherLife(pool,'wheel-owner',value,new Date(),cap);commands.push({type:value.type,payload:value.type.startsWith('minigame.')?{kind:value.payload.kind,characterId:value.payload.characterId,practice:value.payload.practice}:undefined,ok:response.ok,error:response.error,at:new Date().toISOString()});return response;}return{ok:false};});
 await context.route('opui://**',route=>{const rel=decodeURIComponent(new URL(route.request().url()).pathname).replace(/^\//,''),target=source('public/'+rel);requested.push(rel);if(rel.includes('..')||!fs.existsSync(target)){missing.push(rel);return route.fulfill({status:404,body:'missing'});}return route.fulfill({path:target});});page=await context.newPage();page.on('pageerror',e=>errors.push(e.stack||e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/launcher.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.body.dataset.stage==='app');await page.locator('.nav-button[data-panel="profile"]').click();await page.waitForFunction(()=>window.__launcherRoomTest?.snapshot()?.life?.ownedCharacterIds?.includes('room-character-robin'),null,{timeout:20000});
 await check('actual-profile-room-loads-new-robin-atlases',async()=>{await page.waitForFunction(()=>__launcherRoomTest.snapshot().walkers[0]?.ready.length===4);assert(requested.some(p=>p.endsWith('robin_v2/portrait.webp')));for(const direction of ['east','west','north','south'])assert(requested.some(p=>p.endsWith('robin_v2/walk/'+direction+'.webp')));assert.equal(await page.locator('#roomCharacters [data-room-key]').count(),1);});
 await check('click-robin-wheel-opens-work-intro-without-spending',async()=>{await chooseRobin();await capture('room-wheel-robin-desktop');const count=commands.filter(c=>c.type==='minigame.start').length;await wheelAction('roomLifeWork');assert.match(await page.locator('#roomMinigameTitle').innerText(),/海上補給/);assert.equal(commands.filter(c=>c.type==='minigame.start').length,count);assert.match(await page.locator('#roomMinigamePortrait').getAttribute('src'),/robin_v2\/portrait.webp$/);await capture('room-wheel-work-robin-desktop');await closeIntro();});
 await check('keyboard-wheel-training-starts-robin-whole-figure-and-keeps-modal-focus',async()=>{await chooseRobin();await wheelAction('roomLifeTrain');assert.match(await page.locator('#roomMinigameTitle').innerText(),/甲板特訓/);await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('.room-minigame-runner')?.dataset.wholeBody==='true');assert.equal(await page.locator('.room-minigame-runner').evaluate(canvas=>canvas.width),384);await capture('room-wheel-training-robin-desktop');await page.keyboard.press('Escape');await page.waitForFunction(()=>!!document.querySelector('.room-minigame-confirm'));assert.equal(await page.evaluate(()=>document.getElementById('roomMinigameOverlay').contains(document.activeElement)),true);await page.getByRole('button',{name:'結束並回房間'}).click();await page.waitForFunction(()=>document.getElementById('roomMinigameOverlay').hidden);});
 await check('390px-wheel-work-uses-live-entry-and-real-three-cargo-layout',async()=>{await page.setViewportSize({width:390,height:844});await chooseRobin();await wheelAction('roomLifeWork');await page.getByRole('button',{name:'準備好了 · 開始挑戰'}).click();await page.waitForFunction(()=>!!document.querySelector('.room-minigame-cargo')&&!document.querySelector('.room-minigame-cargo').disabled);for(const card of await page.locator('.room-minigame-cargo').all()){const box=await card.boundingBox();assert(box.x>=0&&box.x+box.width<=390);assert.equal(await card.locator('img').evaluate(img=>img.complete&&img.naturalWidth>0),true);}await capture('room-wheel-work-robin-narrow');await cancelGame();});
 await check('390px-robin-training-free-practice-respects-cooldown-and-shows-new-art',async()=>{await chooseRobin();await wheelAction('roomLifeTrain');await page.getByRole('button',{name:'先自由練習 · 不領獎'}).click();await page.getByRole('button',{name:'準備好了 · 開始挑戰'}).click();await page.waitForFunction(()=>document.querySelector('.room-minigame-runner')?.dataset.wholeBody==='true');await capture('room-wheel-training-robin-narrow');assert.equal(await page.locator('#roomMinigamePortrait').evaluate(img=>img.complete&&img.naturalWidth>0),true);await cancelGame();});
 await check('leaving-profile-cancels-session-and-closes-overlay',async()=>{await chooseRobin();await wheelAction('roomLifeTrain');await page.getByRole('button',{name:'先自由練習 · 不領獎'}).click();await page.getByRole('button',{name:'準備好了 · 開始挑戰'}).click();await page.waitForFunction(()=>!!document.querySelector('.room-minigame-runner'));await page.evaluate(()=>window.LauncherProfileShop.onVisible('library'));await page.waitForFunction(()=>document.getElementById('roomMinigameOverlay').hidden);await page.waitForTimeout(200);assert.equal((await B.getLauncherLife(pool,'wheel-owner',new Date(),cap)).activeMinigame,null);});
 await check('robin-new-art-and-all-game-art-no-missing-resource-or-script-error',async()=>{assert.deepEqual(missing,[]);assert.deepEqual(errors,[]);assert.deepEqual(before,bindings());});
 const assets=[...new Set(requested.filter(p=>p.includes('robin_v2/')||p.includes('minigames_v1/')))].sort();const report={schema:'room-wheel-minigames-integration/1',status:'PASS',createdAt:new Date().toISOString(),checks,captures,sourceSha256:before,assetSha256:Object.fromEntries(assets.map(file=>['public/'+file,sha(fs.readFileSync(source('public/'+file)))])),commands,missing,errors,limitations:['Production HTML/CSP/scripts and actual room-wheel entry, real service functions with isolated PGlite.','Automated desktop/narrow Chromium, not human or physical-device acceptance.','No production account or live purchase.']};fs.writeFileSync(path.join(out,'ROOM_WHEEL_INTEGRATION_QA.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'PASS',passed:checks.length,captures:captures.length}));
}
main().catch(async error=>{fs.writeFileSync(path.join(out,'ROOM_WHEEL_INTEGRATION_FAILURE.json'),JSON.stringify({error:error.stack,checks,commands,missing,errors,snapshot:await page?.evaluate(()=>window.__launcherRoomTest?.snapshot()).catch(()=>null)},null,2));await page?.screenshot({path:path.join(out,'room-wheel-failure.png')}).catch(()=>{});console.error(error);process.exitCode=1;}).finally(async()=>{await browser?.close();await new Promise(resolve=>server?server.close(resolve):resolve());await db.close();});
