'use strict';
// Real Chromium, production HTML/CSP/modules and real service over isolated SQL.
// Uses real wall time for rounds. Not a human playtest or live-account purchase.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {PGlite}=require(process.env.BOARD_QA_PGLITE||'D:/Codex_QA/draw-result-art-20260922/deps/node_modules/@electric-sql/pglite');
const runtimeBase=path.join(process.env.LOCALAPPDATA,'OpenAI/Codex/runtimes/cua_node');
const runtime=process.env.BOARD_QA_PLAYWRIGHT||fs.readdirSync(runtimeBase).map(name=>path.join(runtimeBase,name,'bin/node_modules/playwright')).find(file=>fs.existsSync(file));
const {chromium}=require(runtime);
const root=process.env.LAUNCHER_MINIGAMES_SOURCE_ROOT||path.resolve(__dirname,'..'),overlay=process.env.LAUNCHER_MINIGAMES_OVERLAY||root,out=process.env.LAUNCHER_MINIGAMES_QA_OUT||path.join(overlay,'tools/launcher-room/expansion-v128/review-evidence/client');
const source=file=>fs.existsSync(path.join(overlay,file))?path.join(overlay,file):path.join(root,file);
const temp=process.env.LAUNCHER_MINIGAMES_QA_TEMP||path.join(overlay,'tools/launcher-room/expansion-v128/browser-temp');fs.mkdirSync(out,{recursive:true});fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const B=require(path.join(root,'server/launcher-life-store')),S=require(path.join(root,'server/launcher-profile-shop')),db=new PGlite(),checks=[],captures=[],errors=[],commands=[];let tail=Promise.resolve(),seq=0,browser,server,page,context;
const pool={query:(...args)=>db.query(...args),async connect(){const previous=tail;let release;tail=new Promise(resolve=>release=resolve);await previous;return{query:(...args)=>db.query(...args),release};}};
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const sourceFiles=['desktop/launcher-room-minigames.js','desktop/launcher-room-minigames.css','desktop/launcher-life-room.js','desktop/auth-service.js','desktop/launcher.html','server/launcher-life-store.js','server/launcher-minigames.js','scripts/launcher_room_expansion_client_qa.js'];
const sourceHashes=()=>Object.fromEntries(sourceFiles.map(file=>[file,sha(fs.readFileSync(source(file)))]));
const cap={crewContentRevision:1};
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function add(secret){const keys=['robin','nami','ace','luffy','zoro','usopp','sanji','chopper','franky','brook','jinbe'],today=new Date().toISOString().slice(0,10);await db.query('INSERT INTO player_profiles(secret,name,avatar,stats) VALUES($1,$1,$2,$3::jsonb)',[secret,'8',JSON.stringify({client:{totals:{coins:73}},launcherWalletV1:{coins:100,lastGrantDay:today},launcherOwnedV1:{items:keys.map(k=>'room-character-'+k)},launcherRoomV1:{revision:1,sceneId:'room-scene-default',capacityVersion:2,placements:[],characters:keys.map((k,i)=>({itemId:'room-character-'+k,x:160+i*70,y:440}))}})]);}
function fixture(){
  const initial={authenticated:false,profile:null,preferences:{},games:{}};
  window.onePieceDesktop={getState:async()=>initial,onState(){},onSocialState(){},onLauncherUpdate(){},onProgress(){},onSessionKicked(){},getSocialState:async()=>({ok:false}),getLauncherUpdateState:async()=>({ok:false}),getLauncherAnnouncements:async()=>({ok:false}),getLauncherShop:async()=>({ok:false}),getLauncherProfile:async()=>({ok:false}),getLauncherComments:async()=>({ok:false}),getLauncherLife:async()=>({ok:false})};
  window.__Q={user:'client-owner',offline:false,dropAnswer:false,hold:false,release:null,opens:0,closes:0,last:null,calls:[]};
}
async function capture(name){const file=name+'.png';await page.screenshot({path:path.join(out,file)});captures.push({path:file,sha256:sha(fs.readFileSync(path.join(out,file))),viewport:page.viewportSize()});}
async function state(){return page.evaluate(()=>__game.inspect());}
async function open(kind,key='nami',jobId='supply'){await page.evaluate(({kind,key,jobId})=>__game.open({kind,jobId,characterId:'room-character-'+key}),{kind,key,jobId});}
async function start(){await page.getByRole('button',{name:'準備好了 · 開始挑戰'}).dblclick();await page.waitForFunction(()=>['showcase','answer','result','rewardPending'].includes(__game.inspect().phase));}
async function waitAnswer(){await page.waitForFunction(()=>__game.inspect().phase==='answer');}
async function close(){await page.getByRole('button',{name:'結束並關閉挑戰'}).click();const confirm=page.getByRole('button',{name:'結束並回房間'});if(await confirm.count())await confirm.click();await page.waitForFunction(()=>!__game.active());}
async function workRound(correct=true,{loseAck=false,timeout=false}={}){
  await waitAnswer();const prior=await state();
  const data=await page.evaluate(()=>__Q.last.minigame.challenge);
  if(!timeout){const indexes=data.crates.map((c,i)=>c.category===data.order.category?i:-1).filter(i=>i>=0);if(correct){for(const index of indexes)await page.keyboard.press(String(index+1));}else{const index=data.crates.findIndex(c=>c.category!==data.order.category);await page.keyboard.press(String(index+1));}if(loseAck)await page.evaluate(()=>__Q.dropAnswer=true);await page.keyboard.press('Enter');}
  await page.waitForFunction(index=>__game.inspect().roundIndex!==index||['result','retry'].includes(__game.inspect().phase),prior.roundIndex,{timeout:18000});
}
async function trainingRound(correct=true){await waitAnswer();const old=await state(),data=await page.evaluate(()=>__Q.last.minigame.challenge);for(const direction of correct?data.directions:data.directions.map(d=>d==='left'?'right':'left')){await page.keyboard.press({left:'ArrowLeft',up:'ArrowUp',right:'ArrowRight'}[direction]);await page.waitForTimeout(120);}await page.waitForFunction(index=>__game.inspect().roundIndex!==index||__game.inspect().phase==='result',old.roundIndex,{timeout:18000});}
function solveRepair(round){
 const side=['north','east','south','west'],offset=[-3,1,3,-1],rotations=round.tiles.map(tile=>tile.rotation);
 function visit(index,enter,seen,current){
  for(let turn=0;turn<4;turn++){
   const ports=(round.tiles[index].type==='straight'?[0,2]:[0,1]).map(p=>(p+turn)%4);if(!ports.includes(enter))continue;
   const out=ports.find(p=>p!==enter),next=index+offset[out],candidate=[...current];candidate[index]=turn;
   if(index===round.exit.index&&out===side.indexOf(round.exit.side))return candidate;
   if(next<0||next>=9||seen.has(next)||Math.abs(index%3-next%3)+Math.abs(Math.floor(index/3)-Math.floor(next/3))!==1)continue;
   const found=visit(next,(out+2)%4,new Set([...seen,next]),candidate);if(found)return found;
  }return null;
 }
 const answer=visit(round.entry.index,side.indexOf(round.entry.side),new Set([round.entry.index]),rotations);assert(answer,'Independent pipe solver found a path');return answer;
}
function solveNavigation(round){const queue=[[round.start]],seen=new Set([round.start]);while(queue.length){const course=queue.shift(),last=course.at(-1);if(last===round.goal){assert(course.length-1<=round.maxSteps);return course;}for(const next of [last-4,last+1,last+4,last-1])if(next>=0&&next<16&&!seen.has(next)&&!round.blocked.includes(next)&&Math.abs(last%4-next%4)+Math.abs(Math.floor(last/4)-Math.floor(next/4))===1){seen.add(next);queue.push([...course,next]);}}throw new Error('Navigation chart is unreachable');}
async function nextRound(old){await page.waitForFunction(index=>__game.inspect().roundIndex!==index||['result','retry'].includes(__game.inspect().phase),old,{timeout:22000});}
async function playJobRound({correct=true,first=false,loseAck=false,timeout=false}={}){
 await waitAnswer();const before=await state(),round=await page.evaluate(()=>__Q.last.minigame.challenge);
 if(!timeout){
  if(before.jobId==='cooking'){
   const ids=correct?round.recipe:[round.ingredients.find(i=>i.id!==round.recipe[0]).id];
   if(first){await page.locator('.room-minigame-ingredient').first().click();assert.equal((await state()).ingredients.length,1);await page.keyboard.press('Backspace');assert.equal((await state()).ingredients.length,0);}
   for(const id of ids)await page.keyboard.press(String(round.ingredients.findIndex(i=>i.id===id)+1));
  }else if(before.jobId==='repair'){
   if(first){const initial=[...(await state()).rotations];await page.locator('[data-pipe="0"]').click();assert.equal((await state()).rotations[0],(initial[0]+1)%4);await page.getByRole('button',{name:'還原管線'}).click();assert.deepEqual((await state()).rotations,initial);}
   if(correct){const goal=solveRepair(round),current=(await state()).rotations;for(let index=0;index<9;index++)for(let n=0;n<(goal[index]-current[index]+4)%4;n++)await page.keyboard.press(String(index+1));}
  }else{
   const route=solveNavigation(round);
   if(first){const old=[...(await state()).course],distant=Array.from({length:16},(_,i)=>i).find(i=>!round.blocked.includes(i)&&Math.abs(i%4-round.start%4)+Math.abs(Math.floor(i/4)-Math.floor(round.start/4))>1);await page.locator(`[data-cell="${distant}"]`).click();assert.deepEqual((await state()).course,old);await page.locator(`[data-cell="${route[1]}"]`).click();await page.keyboard.press('Backspace');assert.deepEqual((await state()).course,old);}
   if(correct){for(let index=1;index<route.length;index++){const delta=route[index]-route[index-1];if(index%2)await page.keyboard.press({'-4':'ArrowUp','4':'ArrowDown','-1':'ArrowLeft','1':'ArrowRight'}[String(delta)]);else await page.locator(`[data-cell="${route[index]}"]`).click();}assert.deepEqual((await state()).course,route);}
  }
  if(loseAck)await page.evaluate(()=>__Q.dropAnswer=true);await page.keyboard.press('Enter');
 }
 await nextRound(before.roundIndex);
}
const requested=new Set(),missing=[];
async function main(){
 const before=sourceHashes();await db.exec('CREATE TABLE player_profiles(user_id SERIAL PRIMARY KEY,secret TEXT UNIQUE NOT NULL,name TEXT,avatar TEXT,stats JSONB,updated_at TIMESTAMPTZ DEFAULT now())');for(const user of ['client-owner','client-narrow','client-recovery','client-failure','client-race'])await add(user);
 server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\//,'')||'launcher.html';if(rel.includes('..')){res.writeHead(404);res.end();return;}const target=source('desktop/'+rel);if(!fs.existsSync(target)){res.writeHead(404);res.end();return;}const ext=path.extname(target);res.setHeader('Content-Type',ext==='.js'?'text/javascript':ext==='.css'?'text/css':'text/html');res.end(fs.readFileSync(target));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browserBase=path.join(process.env.LOCALAPPDATA,'ms-playwright'),executablePath=process.env.BOARD_QA_CHROMIUM||fs.readdirSync(browserBase).filter(n=>/^chromium-/.test(n)).sort().reverse().map(name=>path.join(browserBase,name,'chrome-win64/chrome.exe')).find(file=>fs.existsSync(file));
 browser=await chromium.launch({headless:true,...executablePath?{executablePath}:{},args:['--disable-gpu-shader-disk-cache']});context=await browser.newContext({viewport:{width:1280,height:900}});await context.addInitScript(fixture);await context.route('opui://**',route=>{const rel=decodeURIComponent(new URL(route.request().url()).pathname).replace(/^\//,''),target=source('public/'+rel);requested.add('public/'+rel);if(rel.includes('..')||!fs.existsSync(target)){missing.push(rel);return route.fulfill({status:404,body:'missing'});}return route.fulfill({path:target});});
 await context.exposeFunction('__serviceCommand',async(user,type,payload)=>{const snap=await B.getLauncherLife(pool,user,new Date(),cap);const result=await B.commandLauncherLife(pool,user,{type,payload,requestId:'expansion-real-'+String(++seq).padStart(8,'0'),expectedRevision:snap.life.revision},new Date(),cap);commands.push({user,type,jobId:payload.jobId,ok:result.ok,error:result.error,roundIndex:result.minigame?.roundIndex,at:new Date().toISOString()});return result;});
 page=await context.newPage();page.on('pageerror',error=>errors.push(error.stack||error.message));await page.goto('http://127.0.0.1:'+server.address().port+'/launcher.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!window.OnePieceRoomMinigames);
 await page.evaluate(()=>{window.__game=OnePieceRoomMinigames.create({command:async(type,payload)=>{const owner=__Q.user;__Q.calls.push({type,owner});if(__Q.offline)return{ok:false,error:'offline'};const response=await __serviceCommand(owner,type,payload);if(__Q.hold)await new Promise(resolve=>__Q.release=resolve);if(type==='minigame.answer'&&__Q.dropAnswer){__Q.dropAnswer=false;return{ok:false,error:'offline'};}__Q.last=response;return response;},onOpen:()=>__Q.opens++,onClose:()=>__Q.closes++});});
 await check('four-work-cards-free-selection-shared-budget-and-supply-default',async()=>{await open('work');assert.equal((await state()).jobId,'supply');assert.equal(await page.locator('.room-minigame-job').count(),4);for(const id of ['cooking','repair','navigation','supply']){await page.locator(`[data-job="${id}"]`).click();assert.equal((await state()).jobId,id);assert.equal(await page.locator(`[data-job="${id}"]`).getAttribute('aria-pressed'),'true');}assert.equal(commands.length,0);assert.match(await page.locator('.room-minigame-shared-budget').innerText(),/共用/);await capture('four-jobs-desktop');await close();});
 await check('all-eleven-characters-have-distinct-new-job-briefs',async()=>{const keys=await page.evaluate(()=>Object.keys(OnePieceRoomMinigames.VOICES));for(const id of ['cooking','repair','navigation']){const quotes=[];for(const key of keys){await open('work',key,id);quotes.push(await page.locator('[data-testid="minigame-feedback"]').innerText());await close();}assert.equal(new Set(quotes).size,11);}assert.equal(commands.length,0);});
 for(const [id,key] of [['cooking','sanji'],['repair','franky'],['navigation','nami']]){
  await check(`${id}-eight-real-rounds-keyboard-mouse-undo-and-ten-shop-coins`,async()=>{await open('work',key);await page.locator(`[data-job="${id}"]`).click();await start();await waitAnswer();assert.equal((await state()).jobId,id);await capture(id+'-active-desktop');await playJobRound({first:true,loseAck:id==='cooking'});if(id==='cooking'){assert.equal((await state()).phase,'retry');await page.getByRole('button',{name:'重新送出這一輪'}).click();await page.waitForFunction(()=>['showcase','answer'].includes(__game.inspect().phase));assert.equal((await state()).roundIndex,1);}while((await state()).roundIndex<8&&(await state()).phase!=='result')await playJobRound();await page.waitForFunction(()=>__game.inspect().phase==='result');assert.match(await page.locator('.room-minigame-rewards').innerText(),/商城金幣 \+10/);assert.equal(await page.evaluate(()=>__Q.last.minigame.result.correctRounds),8);await capture(id+'-result-desktop');await close();});
 }
 await check('three-jobs-share-one-wallet-and-daily-ledger',async()=>{const snap=await B.getLauncherLife(pool,'client-owner',new Date(),cap);assert.equal(snap.wallet.coins,130);const stats=(await db.query('SELECT stats FROM player_profiles WHERE secret=$1',['client-owner'])).rows[0].stats;assert.equal(stats.launcherCompanionsV1.workStartsToday,3);assert.equal(commands.filter(c=>c.type==='minigame.finish'&&c.ok).length,3);});
 await check('390px-work-picker-and-puzzle-controls-remain-onscreen',async()=>{await page.setViewportSize({width:390,height:844});await page.evaluate(()=>__Q.user='client-narrow');await open('work','robin');await capture('four-jobs-narrow');await close();for(const [id,key] of [['cooking','sanji'],['repair','franky'],['navigation','nami']]){await open('work',key,id);await start();await waitAnswer();await capture(id+'-active-narrow');const selector={cooking:'.room-minigame-ingredient',repair:'.room-minigame-pipe',navigation:'.room-minigame-sea-cell'}[id];for(const b of await page.locator(selector).all()){const box=await b.boundingBox();assert(box.x>=0&&box.x+box.width<=390,`${id} control horizontal bounds`);assert(box.width>=44&&box.height>=44,`${id} touch target`);}assert.equal(await page.locator('.room-minigame-card').evaluate(el=>el.scrollWidth>el.clientWidth),false);await close();}assert.equal((await B.getLauncherLife(pool,'client-narrow',new Date(),cap)).activeMinigame,null);});
 await check('navigation-reef-stays-disabled-after-answer-and-keyboard-cancel-focus',async()=>{await page.evaluate(()=>__Q.user='client-recovery');await open('work','nami','navigation');await start();await waitAnswer();for(const reef of await page.locator('[data-reef="true"]').all())assert.equal(await reef.isDisabled(),true);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.querySelector('.room-minigame-confirm').contains(document.activeElement)),true);await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'繼續挑戰');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'roomMinigameOverlay');await playJobRound();await waitAnswer();for(const reef of await page.locator('[data-reef="true"]').all())assert.equal(await reef.isDisabled(),true);const answered=commands.filter(c=>c.type==='minigame.answer').length;await page.keyboard.press('Escape');await page.keyboard.press('Enter');await page.waitForFunction(()=>!__game.active());assert.equal(commands.filter(c=>c.type==='minigame.answer').length,answered);assert.equal((await B.getLauncherLife(pool,'client-recovery',new Date(),cap)).activeMinigame,null);});
 await check('timeout-partial-cooking-counts-miss-and-failed-game-retries-free',async()=>{await page.evaluate(()=>__Q.user='client-failure');await open('work','sanji','cooking');await start();await playJobRound({timeout:true});assert.equal(await page.evaluate(()=>__Q.last.minigame.correctRounds),0);while((await state()).roundIndex<8&&(await state()).phase!=='result')await playJobRound({correct:false});await page.waitForFunction(()=>__game.inspect().phase==='result');assert.equal(await page.evaluate(()=>__Q.last.minigame.state),'failed');const old=await page.evaluate(()=>__Q.last.minigame.id);await page.getByRole('button',{name:'再試一次 · 不額外消耗'}).click();await page.waitForFunction(()=>__game.inspect().phase==='showcase');assert.equal(await page.evaluate(()=>__Q.last.minigame.id),old);assert.equal(await page.evaluate(()=>__Q.last.minigame.jobId),'cooking');const stats=(await db.query('SELECT stats FROM player_profiles WHERE secret=$1',['client-failure'])).rows[0].stats;assert.equal(stats.launcherCompanionsV1.workStartsToday,1);await close();});
 await check('dismiss-during-new-job-start-never-reopens-for-different-account',async()=>{await page.evaluate(()=>__Q.user='client-race');await open('work','ace','repair');await page.evaluate(()=>__Q.hold=true);await page.getByRole('button',{name:'準備好了 · 開始挑戰'}).click();await page.waitForFunction(()=>!!__Q.release);await page.evaluate(()=>{__game.dismiss();__Q.user='client-owner';__Q.hold=false;__Q.release();});await page.waitForTimeout(300);assert.equal((await state()).phase,'closed');assert.equal(await page.locator('#roomMinigameOverlay').isHidden(),true);});
 await check('new-puzzles-real-assets-no-missing-resources-or-console-errors',async()=>{assert.deepEqual(missing,[]);assert.deepEqual(errors,[]);assert.deepEqual(sourceHashes(),before);});
 const report={schema:'launcher-expansion-client-qa/1',status:'PASS',createdAt:new Date().toISOString(),checks,counts:{passed:checks.length,failed:0},sourceSha256:before,assetSha256:Object.fromEntries([...requested].sort().map(file=>[file,sha(fs.readFileSync(source(file)))])),captures,commands,limitations:['Automated Chromium interaction, not human playtest or physical-device acceptance.','Real service functions and isolated PGlite, no production accounts or PostgreSQL concurrency claim.','Real clocks, independently solved repair/navigation and recipe-driven cooking inputs.','Production HTML/CSP modules; separate room-wheel fixture verifies actual entry.']};fs.writeFileSync(path.join(out,'EXPANSION_CLIENT_QA.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'PASS',passed:checks.length,captures:captures.length,report:path.join(out,'EXPANSION_CLIENT_QA.json')}));
}
main().catch(async error=>{fs.writeFileSync(path.join(out,'EXPANSION_CLIENT_FAILURE.json'),JSON.stringify({status:'FAIL',error:error.stack,checks,commands},null,2));await page?.screenshot({path:path.join(out,'expansion-failure.png')}).catch(()=>{});console.error(error);process.exitCode=1;}).finally(async()=>{await browser?.close();await new Promise(resolve=>server?server.close(resolve):resolve());await db.close();});
