'use strict';
// Real Chrome media decoding/playback with production launcher and isolated IPC.
// No autoplay-policy override, no muted-only success, no physical speaker claim.
const fs = require('node:fs'), path = require('node:path'), http = require('node:http'), crypto = require('node:crypto'), assert = require('node:assert/strict'), vm = require('node:vm');
const root = path.resolve(__dirname, '..'), out = path.join(root, 'tools/launcher-room/presentation-v126/review-evidence');
const scratch = 'D:/Codex_QA/launcher-announcements-1.2.6/profile-bgm-browser-temp'; fs.mkdirSync(scratch, { recursive: true }); process.env.TEMP = scratch; process.env.TMP = scratch;
const { chromium } = require(process.env.BOARD_QA_PLAYWRIGHT || 'C:/Users/王曜瑋/AppData/Local/OpenAI/Codex/runtimes/cua_node/13827bafdc0b5422/bin/node_modules/playwright');
const sha = value => crypto.createHash('sha256').update(value).digest('hex');
const names = ['launcher-profile-shop.js', 'launcher-profile-shop.css', 'launcher.html', 'launcher.js', 'main.js', 'auth-service.js'];
const bindings = () => Object.fromEntries(names.map(name => [name, sha(fs.readFileSync(path.join(root, 'desktop', name)))]));
const sourceSha256 = bindings(), results = [], captures = [], errors = [], audioObservations = [];
const fixturePath = path.join(root, 'scripts/launcher_announcements_client_qa.js'), fixtureSource = fs.readFileSync(fixturePath, 'utf8');
const fixture = vm.runInNewContext('(' + fixtureSource.slice(fixtureSource.indexOf('function fixture('), fixtureSource.indexOf('\nasync function capture(')) + ')');
const catalog = require(path.join(root, 'server/launcher-profile-shop')).CATALOG;
const baseShop = { catalog, owned: { bgms: ['bgm-harbor', 'bgm-night-watch', 'bgm-voyage'] }, equipped: { bgmId: 'bgm-harbor' }, wallet: { coins: 40, cap: 500, dailyGrant: 10 } };
let page, browser, server;
const check = async (name, run) => { await run(); results.push({ name, status: 'PASS' }); console.log('PASS ' + name); };
function musicFixture({ catalog, shop }) {
  const q = window.__noticeQA;
  const m = window.__bgmQA = { songs: { 42: 'bgm-harbor', 84: 'bgm-night-watch', 126: 'bgm-voyage' }, holdProfiles: [], profileResolvers: [], playResolvers: [], holdNextPlay: false, blockNextPlay: false, playCalls: [], override: null,
    profile(id) { const bgmId = m.songs[id], bgm = catalog.find(item => item.id === bgmId) || null; return { userId: id, isSelf: id === q.user, name: id === q.user ? '航海者的個人頁' : '好友的個人頁', avatar: 8, appearance: { bgmId }, appearanceItems: { bgm }, collection: { card: { avatars: [8] }, launcher: { itemIds: shop.owned.bgms } }, games: {}, room: { revision: 1, capacityVersion: 2, sceneId: 'room-scene-default', placements: [], characters: [] }, roomItems: { placements: [], characters: [] }, guestbookUnlocked: false }; },
    shop() { return { ...shop, equipped: { bgmId: m.songs[q.user] || 'bgm-none' } }; },
    releaseProfiles() { m.profileResolvers.splice(0).forEach(resolve => resolve()); }, releasePlays() { m.playResolvers.splice(0).forEach(resolve => resolve()); }
  };
  window.onePieceDesktop.getLauncherProfile = async userId => { const id = userId || q.user; const profile = m.override || m.profile(id); q.calls.push({ kind: 'profile', id }); if (m.holdProfiles.includes(id)) await new Promise(resolve => m.profileResolvers.push(resolve)); return { ok: true, profile }; };
  window.onePieceDesktop.getLauncherShop = async () => ({ ok: true, shop: m.shop() });
  window.onePieceDesktop.equipLauncherItem = async itemId => { q.calls.push({ kind: 'equip', itemId }); if (itemId !== 'bgm-none' && !shop.owned.bgms.includes(itemId)) return { ok: false, error: 'not_owned' }; m.songs[q.user] = itemId; return { ok: true, profile: m.profile(q.user), shop: m.shop() }; };
  const nativePlay = HTMLMediaElement.prototype.play;
  HTMLMediaElement.prototype.play = function () {
    if (this.id !== 'profileBgmAudio') return nativePlay.call(this);
    m.playCalls.push({ src: this.src, muted: this.muted, volume: this.volume });
    if (m.blockNextPlay) { m.blockNextPlay = false; return Promise.reject(new DOMException('Isolated policy-denial fixture', 'NotAllowedError')); }
    const playing = nativePlay.call(this);
    if (m.holdNextPlay) { m.holdNextPlay = false; return playing.then(() => new Promise(resolve => m.playResolvers.push(resolve))); }
    return playing;
  };
}
async function playing(track, unmuted = true, extension = 'ogg') {
  await page.waitForFunction(({ track, unmuted, extension }) => { const a = document.getElementById('profileBgmAudio'); return a.currentSrc.endsWith('/' + track + '.' + extension) && !a.paused && a.currentTime > .12 && a.readyState >= 2 && !a.error && (!unmuted || (!a.muted && a.volume > 0)); }, { track, unmuted, extension }, { timeout: 15000 });
  const observation = await page.evaluate(() => { const a = document.getElementById('profileBgmAudio'); return { src: a.currentSrc, currentTime: a.currentTime, duration: a.duration, paused: a.paused, muted: a.muted, volume: a.volume, readyState: a.readyState, loop: a.loop, error: a.error?.code || null }; });
  audioObservations.push(observation); return observation;
}
async function stopped() { await page.waitForFunction(() => document.getElementById('profileBgmAudio').paused, null, { timeout: 5000 }); }
async function shot(name) { await page.locator('.captain-cabin-music').scrollIntoViewIfNeeded(); const file = name + '.png'; await page.screenshot({ path: path.join(out, file), animations: 'disabled' }); captures.push({ path: file, sha256: sha(fs.readFileSync(path.join(out, file))), viewport: page.viewportSize(), kind: 'Actual Chromium profile music controls; isolated empty-room/profile IPC fixture' }); }
(async () => {
  server = http.createServer((request, response) => {
    const relative = decodeURIComponent(new URL(request.url, 'http://localhost').pathname).replace(/^\//, '') || 'launcher.html', target = path.resolve(root, 'desktop', relative);
    if (!target.startsWith(path.join(root, 'desktop') + path.sep) || !fs.existsSync(target) || !fs.statSync(target).isFile()) { response.writeHead(404); response.end(); return; }
    const ext = path.extname(target); response.setHeader('Content-Type', ext === '.js' ? 'text/javascript' : ext === '.css' ? 'text/css' : 'text/html'); response.end(fs.readFileSync(target));
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', args: ['--disable-gpu-shader-disk-cache'] });
  const context = await browser.newContext({ viewport: { width: 1280, height: 820 }, reducedMotion: 'reduce' });
  await context.addInitScript(fixture, { notices: [], shop: baseShop }); await context.addInitScript(musicFixture, { catalog, shop: baseShop });
  await context.route('opui://**', route => { const target = path.resolve(root, 'public', decodeURIComponent(new URL(route.request().url()).pathname).replace(/^\//, '')); return target.startsWith(path.join(root, 'public') + path.sep) && fs.existsSync(target) ? route.fulfill({ path: target }) : route.fulfill({ status: 404, body: 'not available' }); });
  page = await context.newPage(); page.on('pageerror', error => errors.push(error.stack || error.message)); await page.goto(`http://127.0.0.1:${server.address().port}/launcher.html`, { waitUntil: 'domcontentloaded' }); await page.waitForFunction(() => document.body.dataset.stage === 'app');
  await check('self-entry-autoplays-real-unmuted-looping-ogg', async () => { await page.locator('#profileButton').click(); const a = await playing('harbor'); assert.equal(a.loop, true); assert.equal(a.volume, .35); });
  await check('same-profile-refresh-and-room-render-do-not-restart-song', async () => { const before = await page.evaluate(() => ({ time: profileBgmAudio.currentTime, calls: __bgmQA.playCalls.length })); await page.locator('#profileRefresh').click(); await page.waitForFunction(() => document.getElementById('profileStatus').textContent === ''); await page.evaluate(() => LauncherProfileShop.onRoomSaved(__bgmQA.profile(42), __bgmQA.shop())); const after = await playing('harbor'); assert(after.currentTime >= before.time); assert.equal(await page.evaluate(() => __bgmQA.playCalls.length), before.calls); });
  await check('manual-pause-survives-refresh-and-room-render-until-next-entry', async () => { await page.locator('#profileBgmToggle').click(); await stopped(); const calls = await page.evaluate(() => __bgmQA.playCalls.length); await page.evaluate(() => LauncherProfileShop.onRoomSaved(__bgmQA.profile(42), __bgmQA.shop())); await page.locator('#profileRefresh').click(); await page.waitForFunction(() => document.getElementById('profileStatus').textContent === ''); assert.equal(await page.evaluate(() => profileBgmAudio.paused), true); assert.equal(await page.evaluate(() => __bgmQA.playCalls.length), calls); await page.locator('#announcementsButton').click(); await page.locator('#profileButton').click(); await playing('harbor'); });
  await check('friend-entry-replaces-owner-song-with-single-audio-element', async () => { await page.evaluate(() => LauncherProfileShop.openProfile(84)); await playing('night-watch'); assert.equal(await page.locator('#profilePageTitle').textContent(), '好友個人頁'); assert.equal(await page.locator('audio#profileBgmAudio').count(), 1); });
  await check('late-profile-response-cannot-play-over-new-friend', async () => { await page.evaluate(() => { __bgmQA.holdProfiles = [42]; LauncherProfileShop.openProfile(0); }); await page.evaluate(() => LauncherProfileShop.openProfile(126)); await playing('voyage'); await page.evaluate(() => { __bgmQA.holdProfiles = []; __bgmQA.releaseProfiles(); }); await playing('voyage'); assert.equal(await page.locator('#profileHeroId').textContent(), '航海者 #126'); });
  await check('late-play-promise-cannot-stop-new-friend-song', async () => { await page.evaluate(() => { __bgmQA.holdNextPlay = true; LauncherProfileShop.openProfile(84); }); await page.waitForFunction(() => __bgmQA.playResolvers.length === 1); await page.evaluate(() => LauncherProfileShop.openProfile(126)); const before = await playing('voyage'); await page.evaluate(() => __bgmQA.releasePlays()); await page.waitForFunction(time => profileBgmAudio.currentTime > time + .1 && !profileBgmAudio.paused, before.currentTime); await playing('voyage'); });
  await check('leaving-during-load-stays-silent-and-cached-return-autoplays', async () => { await page.evaluate(() => { __bgmQA.holdProfiles = [42]; LauncherProfileShop.openProfile(0); }); await page.locator('#announcementsButton').click(); await page.evaluate(() => { __bgmQA.holdProfiles = []; __bgmQA.releaseProfiles(); }); await page.waitForFunction(() => document.getElementById('profileBgmAudio').getAttribute('src')?.endsWith('/harbor.ogg')); await stopped(); assert.equal(await page.evaluate(() => profileBgmAudio.currentTime), 0); await page.evaluate(() => launcherSwitchPanel('profile')); await playing('harbor'); });
  await check('shop-equip-persists-selected-song-for-next-own-entry-without-hidden-play', async () => { await page.locator('#shopButton').click(); await page.getByRole('tab', { name: '音樂', exact: true }).click(); await page.locator('.shop-item[data-item-id="bgm-night-watch"] button').click(); await page.waitForFunction(() => __noticeQA.calls.some(c => c.kind === 'equip' && c.itemId === 'bgm-night-watch')); await stopped(); await page.locator('#profileButton').click(); await playing('night-watch'); });
  await check('listener-mute-volume-persist-across-friend-visits-and-reload', async () => {
    await page.locator('#profileBgmMute').click(); assert.equal(await page.evaluate(() => profileBgmAudio.muted), true);
    await page.evaluate(() => { const input = document.getElementById('profileBgmVolume'); input.value = '62'; input.dispatchEvent(new Event('input', { bubbles: true })); });
    await page.evaluate(() => LauncherProfileShop.openProfile(126)); const a = await playing('voyage', false); assert.equal(a.muted, true); assert.equal(a.volume, .62);
    await page.reload({ waitUntil: 'domcontentloaded' }); await page.waitForFunction(() => document.body.dataset.stage === 'app'); await stopped(); await page.locator('#profileButton').click(); const b = await playing('harbor', false); assert.equal(b.muted, true); assert.equal(b.volume, .62); await page.locator('#profileBgmMute').click(); await playing('harbor');
  });
  await check('controlled-visibility-stop-return-and-manual-pause-intent', async () => {
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')); }); await stopped(); assert.equal(await page.evaluate(() => profileBgmAudio.currentTime), 0);
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: false }); document.dispatchEvent(new Event('visibilitychange')); }); await playing('harbor');
    await page.locator('#profileBgmToggle').click(); await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')); Object.defineProperty(document, 'hidden', { configurable: true, value: false }); document.dispatchEvent(new Event('visibilitychange')); }); assert.equal(await page.evaluate(() => profileBgmAudio.paused), true); await page.evaluate(() => { delete document.hidden; });
  });
  await check('injected-autoplay-denial-is-explained-and-one-real-click-recovers', async () => { await page.evaluate(() => { __bgmQA.blockNextPlay = true; LauncherProfileShop.openProfile(84); }); await page.waitForFunction(() => document.getElementById('profileBgmHint').textContent.includes('系統限制')); const calls = await page.evaluate(() => __bgmQA.playCalls.length); await page.locator('#profileRefresh').click(); await page.waitForFunction(() => document.getElementById('profileStatus').textContent === ''); assert.equal(await page.evaluate(() => __bgmQA.playCalls.length), calls); await page.locator('#profileBgmToggle').click(); await playing('night-watch'); });
  await check('no-song-and-invalid-or-mismatched-assets-remain-silent', async () => {
    await page.evaluate(() => { __bgmQA.songs[42] = 'bgm-none'; LauncherProfileShop.openProfile(0); }); await page.waitForFunction(() => document.getElementById('profileBgmToggle').disabled); await stopped(); assert.equal(await page.locator('#profileBgmAudio').getAttribute('src'), null);
    await page.evaluate(() => { __bgmQA.songs[42] = 'bgm-harbor'; const p = __bgmQA.profile(42); p.appearanceItems.bgm = { ...p.appearanceItems.bgm, asset: 'https://untrusted.invalid/track.ogg' }; __bgmQA.override = p; LauncherProfileShop.openProfile(0); }); await page.waitForFunction(() => document.getElementById('profileStatus').textContent === ''); assert.equal(await page.locator('#profileBgmAudio').getAttribute('src'), null); await stopped();
    await page.evaluate(() => { const p = __bgmQA.profile(42); p.appearanceItems.bgm = { ...p.appearanceItems.bgm, id: 'bgm-voyage' }; __bgmQA.override = p; LauncherProfileShop.openProfile(0); }); await page.waitForFunction(() => document.getElementById('profileStatus').textContent === ''); assert.equal(await page.locator('#profileBgmAudio').getAttribute('src'), null);
    await page.evaluate(() => { __bgmQA.override = null; LauncherProfileShop.openProfile(0); }); await playing('harbor');
  });
  await check('existing-op-track01-mp3-autoplays-native-unmuted-in-same-profile-player', async () => { await page.evaluate(() => { __bgmQA.songs[42] = 'bgm-op-01'; LauncherProfileShop.openProfile(0); }); const a = await playing('track01', true, 'mp3'); assert(a.src.endsWith('/audio/bgm/track01.mp3')); assert.equal(a.loop, true); assert.equal(await page.locator('audio#profileBgmAudio').count(), 1); await page.evaluate(() => { __bgmQA.songs[42] = 'bgm-harbor'; LauncherProfileShop.openProfile(0); }); await playing('harbor'); });
  await shot('profile-bgm-desktop');
  await check('desktop-and-390px-music-controls-fit-and-remain-operable', async () => { await page.setViewportSize({ width: 390, height: 844 }); await page.locator('.captain-cabin-music').scrollIntoViewIfNeeded(); const geometry = await page.evaluate(() => ({ width: innerWidth, panelRight: document.querySelector('.captain-cabin-music').getBoundingClientRect().right, controlsRight: document.querySelector('.captain-music-controls').getBoundingClientRect().right, volumeRight: document.getElementById('profileBgmVolumeValue').getBoundingClientRect().right, pageWidth: document.documentElement.scrollWidth })); assert(geometry.panelRight <= geometry.width && geometry.controlsRight <= geometry.width && geometry.volumeRight <= geometry.width && geometry.pageWidth <= geometry.width, JSON.stringify(geometry)); await shot('profile-bgm-narrow'); await page.locator('#profileBgmMute').click(); assert.equal(await page.evaluate(() => profileBgmAudio.muted), true); });
  await check('logout-stops-clears-source-and-no-real-purchase-or-browser-error', async () => { await page.evaluate(() => __noticeQA.switchUser(0)); await stopped(); assert.equal(await page.locator('#profileBgmAudio').getAttribute('src'), null); assert.deepEqual(errors, []); assert.equal(await page.evaluate(() => __noticeQA.calls.filter(c => c.kind === 'buy').length), 0); });
  assert.deepEqual(bindings(), sourceSha256);
  const realAudioAssets = ['public/audio/profile_bgm/harbor.ogg', 'public/audio/profile_bgm/night-watch.ogg', 'public/audio/profile_bgm/voyage.ogg', 'public/audio/bgm/track01.mp3'].map(rel => { const bytes = fs.readFileSync(path.join(root, rel)); return { path: rel, bytes: bytes.length, sha256: sha(bytes) }; });
  const report = { schema: 'one-piece-launcher-profile-bgm-client-qa/1', ok: true, generatedAt: new Date().toISOString(), checks: results.length, results, sourceRoot: root, sourceSha256, sourceNormalizedSha256: Object.fromEntries(names.map(name => [name, sha(fs.readFileSync(path.join(root, 'desktop', name), 'utf8').replace(/\r\n/g, '\n'))])), testScriptSha256: sha(fs.readFileSync(__filename)), fixtureScriptSha256: sha(fs.readFileSync(fixturePath)), realAudioAssets, audioObservations, captures, errors, humanAcceptance: false, scope: 'Actual headless Chromium with production launcher HTML/CSP/CSS/JS, local real Ogg plus existing OP track01 MP3 decoding and unmuted currentTime progression. Isolated profile/shop IPC fixture; no real purchase or database. Policy denial, delayed play/profile promises and document visibility are explicitly controlled fault-injection cases. No autoplay-policy browser override. No physical speaker/listening or real-device acceptance claim.' };
  fs.writeFileSync(path.join(out, 'PROFILE_BGM_CLIENT_QA.json'), JSON.stringify(report, null, 2)); console.log(JSON.stringify({ ok: true, checks: results.length, captures: captures.length, audioObservations: audioObservations.length }));
})().catch(error => { fs.writeFileSync(path.join(scratch, 'failure.json'), JSON.stringify({ ok: false, error: error.stack, results, errors }, null, 2)); console.error(error.stack); process.exitCode = 1; }).finally(async () => { await browser?.close(); if (server) await new Promise(resolve => server.close(resolve)); });
