'use strict';
// Real Chrome and real WebP pixels. IPC is isolated; no account, unlock or purchase.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),Module=require('node:module');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.LAUNCHER_RESERVED_ART_QA_OUT||path.join(root,'tools/launcher-room/presentation-v125/review-evidence/reserved-browser'));
const scratch=process.env.LAUNCHER_RESERVED_ART_SCRATCH||'',keys=(process.env.LAUNCHER_RESERVED_ART_KEYS||'ace,sabo,law,hancock').split(',');
const sha=v=>crypto.createHash('sha256').update(v).digest('hex'),R=require(path.join(root,'desktop/launcher-reserved-crew'));
assert(keys.every(k=>R.RESERVED_KEYS.includes(k)));assert(!fs.existsSync(out),'Use a new output directory');fs.mkdirSync(out,{recursive:true});
process.env.LAUNCHER_LIFE_INTEGRATION_OUT=out;
const helperPath=path.join(root,'scripts/launcher_radial_fixture.js');let source=fs.readFileSync(helperPath,'utf8');
const replace=(before,after)=>{assert(source.includes(before),'Fixture anchor '+before);source=source.replace(before,after);};
replace("const {CATALOG}=require(sourceRoot+'/server/launcher-profile-shop');","const {CATALOG:ACTIVE}=require(sourceRoot+'/server/launcher-profile-shop');const R=require(sourceRoot+'/desktop/launcher-reserved-crew');const CATALOG=[...ACTIVE,...Object.values(R.shopMetadata).map(p=>({...p,id:p.itemId,type:'room_character',price:0}))];");
replace("const files=['launcher-room-dialogue.js'","const files=['launcher-reserved-crew.js','launcher-room-dialogue.js'");
replace('    await page.addScriptTag({content:read(file)});', `    await page.addScriptTag({content:read(file)});
    if(file==='launcher-life.js')await page.evaluate(()=>{const original=OnePieceLife;window.OnePieceLife={...original,create:options=>({...original.create(options),tick:()=>{}})};});`);
replace('viewport:{width:1366,height:1050}','viewport:{width:1366,height:1050},deviceScaleFactor:options.dpr||1');
replace("const file=path.resolve(sourceRoot,'public',rel);",`let file=path.resolve(sourceRoot,'public',rel);if(process.env.LAUNCHER_RESERVED_ART_SCRATCH&&rel.includes('/reserved_v1/')){const m=rel.match(/reserved_v1\\/([^/]+)\\/(portrait|walk|acting|life)(?:\\/([^/]+))?\\.webp$/);if(m){const stem=m[2]==='portrait'?'portrait-south':m[2]==='life'?m[3]:m[2]+'-'+m[3];file=path.join(process.env.LAUNCHER_RESERVED_ART_SCRATCH,m[1],stem+'.webp');}}`);
replace("return file.startsWith(path.join(sourceRoot,'public')+path.sep)&&fs.existsSync(file)?", "return (file.startsWith(path.join(sourceRoot,'public')+path.sep)||(process.env.LAUNCHER_RESERVED_ART_SCRATCH&&file.startsWith(path.resolve(process.env.LAUNCHER_RESERVED_ART_SCRATCH)+path.sep)))&&fs.existsSync(file)?");
replace("  await page.evaluate(async()=>{const promises=[];for(const key of window.__integration.db[42].life.ownedCharacterIds.map(id=>id.replace('room-character-','')))for(const clip of ['work','eat','train']){const record=window.OnePieceLifeActions.preload(key,clip,'south');if(record?.promise)promises.push(record.promise);}await Promise.all(promises);});",'');
const mod=new Module(helperPath,module);mod.filename=helperPath;mod.paths=Module._nodeModulePaths(path.dirname(helperPath));mod._compile(source,helperPath);const fixture=mod.exports;
const sourceFiles=['launcher-reserved-crew.js','launcher-room.js','launcher-room-motion.js','launcher-room-motion-data.js','launcher-life-actions.js','launcher-life-data.js','launcher-room-dialogue.js','launcher-life.js','launcher-life-room.js','launcher-room.css','launcher.html'];
const bindings=normalized=>Object.fromEntries(sourceFiles.map(file=>{let value=fs.readFileSync(path.join(root,'desktop',file));if(normalized)value=value.toString('utf8').replace(/\r\n/g,'\n');return[file,sha(value)];}));
const sourceSha256=bindings(false),sourceNormalizedSha256=bindings(true),assetRecords=[],results=[],captures=[];let browser;
const previewOnly=!!scratch||keys.length!==4;
const skipCapture=process.env.LAUNCHER_RESERVED_ART_SKIP_CAPTURE==='1';assert(!skipCapture||previewOnly,'Final QA must capture all evidence');
const manifestPath=path.join(root,'tools/launcher-room/reserved-v1/manifest.json');
const manifest=previewOnly?null:{path:'tools/launcher-room/reserved-v1/manifest.json',sha256:sha(fs.readFileSync(manifestPath))};
const manifestData=previewOnly?null:JSON.parse(fs.readFileSync(manifestPath,'utf8'));
if(manifestData){assert.equal(manifestData.status,'PASS');assert.equal(manifestData.fixtureSources,false);assert.equal(manifestData.items.length,68);assert.equal(manifestData.contactSheets.length,4);}
if(manifestData)assert.equal(require(path.join(root,'tools/launcher-room/presentation-v125/validate_reserved.js')).validate(root,manifestData).complete,true,'Final browser QA requires a genuine validated atlas export');
function assets(key){return [{key,kind:'portrait',direction:'south',cell:256,frames:1,relative:'portrait.webp'},...['east','west','north','south'].flatMap(direction=>[{key,kind:'walk',direction,cell:384,frames:4,relative:`walk/${direction}.webp`},{key,kind:'acting',direction,cell:256,frames:8,relative:`acting/${direction}.webp`},{key,kind:'life',action:'work',direction,cell:256,frames:4,relative:`life/work-${direction}.webp`}]),...['eat','rest','sleep','train'].map(action=>({key,kind:'life',action,direction:'south',cell:256,frames:4,relative:`life/${action}-south.webp`}))];}
function assetPath(item){return scratch?path.join(scratch,item.key,item.kind==='portrait'?'portrait-south.webp':item.kind==='life'?item.relative.slice(5):item.kind+'-'+item.direction+'.webp'):path.join(root,'public/images/launcher_room/reserved_v1',item.key,item.relative);}
for(const key of keys)for(const item of assets(key)){const filename=assetPath(item);assert(fs.existsSync(filename),'Missing real artwork '+filename);assetRecords.push({...item,path:path.relative(root,filename).split(path.sep).join('/'),sha256:sha(fs.readFileSync(filename)),bytes:fs.statSync(filename).size});}
if(manifestData)for(const asset of assetRecords){const bound=manifestData.items.find(item=>item.asset===asset.path);assert(bound&&bound.sha256===asset.sha256,'Real asset must match genuine manifest '+asset.path);}
function state(){const products=Object.values(R.shopMetadata).map(p=>({...p,id:p.itemId,type:'room_character',price:0}));
  const chars=keys.map((key,i)=>({itemId:'room-character-'+key,x:210+i*165,y:422})),ids=chars.map(c=>c.itemId),stamp={releasedCharacterIds:R.SUPPORTED_KEYS.map(k=>'room-character-'+k),rosterRevision:2};
  const life={schemaVersion:1,revision:1,ownedCharacterIds:ids,activeCharacterIds:ids,characters:Object.fromEntries(keys.map(key=>['room-character-'+key,{key,itemId:'room-character-'+key,needs:{energy:85,hunger:20,mood:70,social:70,workMotivation:70},memories:[]}])),pairs:{},jobs:[],pendingArrivals:[],directive:'free_day',recentEvents:[],offlineSummary:{elapsedMs:0,completedJobs:0,coins:0}};
  const room={revision:1,capacityVersion:2,sceneId:'room-scene-default',characters:chars,placements:[]};const profile={userId:42,isSelf:true,name:'預載角色隔離動作驗證',...stamp,life,room,collection:{launcher:{itemIds:ids}},roomItems:{scene:null,placements:[],characters:chars.map(c=>({...c,item:products.find(p=>p.id===c.itemId)}))},companions:chars.map(c=>({itemId:c.itemId,affinity:12,talksRemainingToday:6}))};return{profile,life,wallet:{coins:100,cap:500},...stamp};}
async function capture(page,name){if(skipCapture)return '';const filename=path.join(out,name+'.png');await page.locator('#roomStage').screenshot({path:filename,animations:'allow'});const bytes=fs.readFileSync(filename);captures.push({name,path:path.basename(filename),sha256:sha(bytes),bytes:bytes.length,dimensions:[bytes.readUInt32BE(16),bytes.readUInt32BE(20)]});return filename;}
async function fresh(dpr){const f=await fixture.create({persisted:state(),dpr});await f.page.evaluate(()=>document.getElementById('roomStage').scrollIntoView({block:'center',behavior:'instant'}));await f.page.evaluate(async keys=>{for(const key of keys){await OnePieceRoomMotion.preload(key).promise;await OnePieceRoomMotion.preloadActions(key).promise;for(const action of ['work','eat','rest','sleep','train'])for(const direction of action==='work'?['east','west','north','south']:['south'])await OnePieceLifeActions.preload(key,action,direction).promise;}},keys);return f;}
async function nativePixels(page,dpr){const values=await page.evaluate(async items=>{const output=[];
  for(const item of items){const source=OnePieceReservedCrew.assetUrl(item.key,item.relative),image=new Image();image.src=source;await image.decode();
    if(image.naturalWidth!==item.cell*item.frames||image.naturalHeight!==item.cell)throw Error('Decode dimensions '+source);
    const canvas=document.createElement('canvas'),expected=document.createElement('canvas');canvas.getContext('2d',{willReadFrequently:true});expected.width=expected.height=item.cell;const ec=expected.getContext('2d',{willReadFrequently:true});
    for(let frame=0;frame<item.frames;frame++){let drawn;
      if(item.kind==='walk'||item.kind==='acting'){const record=item.kind==='walk'?OnePieceRoomMotion.preload(item.key):OnePieceRoomMotion.preloadActions(item.key);await record.promise;drawn=OnePieceRoomMotion.draw(canvas,record.atlases[item.direction],frame,item.kind==='walk'?OnePieceRoomMotion.WALK_SHAPE:OnePieceRoomMotion.ACTION_SHAPE);}
      else if(item.kind==='life')drawn=OnePieceLifeActions.draw(canvas,item.key,item.action,item.direction,frame*OnePieceLifeActions.CLIPS[item.action].frameMs);
      else {canvas.width=canvas.height=item.cell;canvas.getContext('2d').drawImage(image,0,0);drawn=true;}
      if(!drawn||canvas.width!==item.cell||canvas.height!==item.cell)throw Error('Native canvas size '+source);
      ec.clearRect(0,0,item.cell,item.cell);ec.drawImage(image,frame*item.cell,0,item.cell,item.cell,0,0,item.cell,item.cell);
      const actual=canvas.getContext('2d',{willReadFrequently:true}).getImageData(0,0,item.cell,item.cell).data,reference=ec.getImageData(0,0,item.cell,item.cell).data;
      let different=0,opaque=0,left=item.cell,top=item.cell,right=0,bottom=0;
      for(let i=0;i<actual.length;i++){if(actual[i]!==reference[i])different++;if(i%4===3&&actual[i]){const p=(i-3)/4,x=p%item.cell,y=Math.floor(p/item.cell);left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x+1);bottom=Math.max(bottom,y+1);if(actual[i]>128)opaque++;}}
      if(different||!opaque||left<=0||top<=0||right>=item.cell||bottom>=item.cell)throw Error('Crop mismatch or clipping '+source+' frame '+frame+' difference '+different);
      output.push({key:item.key,relative:item.relative,frame,canvas:[canvas.width,canvas.height],bounds:[left,top,right,bottom],opaquePixels:opaque,differentChannels:different});
    }
  }return output;},assetRecords);results.push({name:'dpr'+dpr+'-all-real-assets-native-decode-and-crop',status:'PASS',assetCount:assetRecords.length,frameCount:values.length,frames:values});}
async function walking(dpr){for(const direction of ['east','west','north','south']){const f=await fresh(dpr),page=f.page;try{
  assert(await page.evaluate(({keys,direction})=>keys.every(key=>{__launcherRoomTest.lifeCancel(key);const w=__launcherRoomTest.snapshot().walkers.find(v=>v.key===key);return __launcherRoomTest.route(key,{col:w.cell.col+(direction==='east'?2:direction==='west'?-2:0),row:w.cell.row+(direction==='south'?2:direction==='north'?-2:0)});}),{keys,direction}));
  // Public route API deliberately completes a segment already in progress before turning.
  for(let i=0;i<200;i++){const s=await fixture.snap(page);if(keys.every(key=>s.walkers.some(w=>w.key===key&&w.direction===direction)&&s.nodes.some(n=>n.key===key&&n.pose==='walk')))break;await fixture.advance(page,100);}
  const before=await fixture.snap(page);
  const trail=[];for(let i=0;i<18;i++){await fixture.advance(page,100);const current=await fixture.snap(page);const dom=await page.locator('#roomCharacters [data-room-key]').evaluateAll(nodes=>nodes.map(node=>({key:node.dataset.roomKey.replace('c:room-character-',''),direction:node.dataset.direction,pose:node.dataset.pose,frame:node.dataset.motionFrame,canvas:[node.querySelector('canvas').width,node.querySelector('canvas').height]})));trail.push({at:i*100+100,walkers:current.walkers,dom});if(i%2===0)await capture(page,`dpr${dpr}-walk-${direction}-${String(i/2).padStart(2,'0')}`);}
  fs.writeFileSync(path.join(out,`dpr${dpr}-walk-${direction}-trail.json`),JSON.stringify(trail,null,2));
  for(const key of keys){const samples=trail.flatMap(t=>t.dom.filter(n=>n.key===key&&n.pose==='walk'&&n.direction===direction));assert(samples.length>3,'Real route must walk '+key+'/'+direction);assert(samples.every(s=>s.canvas[0]===384&&s.canvas[1]===384),'Walking canvas must preserve384px');assert(new Set(samples.map(s=>s.frame)).size===4,'Real distance-driven cycle covers4frames '+key+'/'+direction+' observed '+samples.map(s=>s.frame));const a=before.walkers.find(w=>w.key===key),b=trail.at(-1).walkers.find(w=>w.key===key);assert(Math.hypot(a.x-b.x,a.y-b.y)>10,'Root advances while authored gait advances');}
  results.push({name:`dpr${dpr}-real-route-${direction}`,status:'PASS',samples:trail});
  assert.deepEqual(f.errors,[]);
}finally{await page.close();}}}
async function selection(page,dpr){for(const key of keys){await page.locator(`[data-room-key="c:room-character-${key}"]`).click();await fixture.advance(page,350);const before=(await fixture.snap(page)).walkers.find(w=>w.key===key),calls=await page.evaluate(()=>__integration.calls.length);assert(before.attention&&before.direction==='south');
  await fixture.advance(page,2200);const after=(await fixture.snap(page)).walkers.find(w=>w.key===key);assert(after.attention&&after.direction==='south');assert.equal(after.x,before.x);assert.equal(after.y,before.y);assert.equal(await page.evaluate(()=>__integration.calls.length),calls);
  const dom=await page.locator(`[data-room-key="c:room-character-${key}"]`).evaluate(n=>({direction:n.dataset.direction,pose:n.dataset.pose,source:n.dataset.actionSource,frame:n.dataset.actionFrame,canvas:[n.querySelector('canvas').width,n.querySelector('canvas').height]}));assert.equal(dom.direction,'south');assert.equal(dom.source,'acting_v4');assert.equal(dom.pose,'idle');assert.deepEqual(dom.canvas,[256,256]);await capture(page,`dpr${dpr}-selected-${key}`);results.push({name:`dpr${dpr}-selected-${key}-front-and-still`,status:'PASS',before,after,dom});await page.locator('#roomCompanionClose').click();await fixture.advance(page,200);
}}
async function gallery(page,dpr){for(const direction of ['east','west','north','south'])for(let frame=0;frame<8;frame++){
  await page.evaluate(({keys,direction,frame})=>{for(const key of keys){const node=document.querySelector(`[data-room-key="c:room-character-${key}"]`),canvas=node.querySelector('.room-walk-sprite');OnePieceRoomMotion.draw(canvas,OnePieceRoomMotion.preloadActions(key).atlases[direction],frame,OnePieceRoomMotion.ACTION_SHAPE);node.dataset.pose=OnePieceRoomMotion.ACTION_POSES[frame];node.dataset.direction=direction;node.dataset.actionSource='acting_v4';}}, {keys,direction,frame});await capture(page,`dpr${dpr}-acting-${direction}-${frame}`);
  }for(const action of ['work','eat','rest','sleep','train'])for(let frame=0;frame<4;frame++){
  await page.evaluate(({keys,action,frame})=>{for(const key of keys){const node=document.querySelector(`[data-room-key="c:room-character-${key}"]`);OnePieceLifeActions.draw(node.querySelector('.room-walk-sprite'),key,action,'south',frame*OnePieceLifeActions.CLIPS[action].frameMs);node.dataset.pose=action;node.dataset.direction='south';}}, {keys,action,frame});await capture(page,`dpr${dpr}-life-${action}-${frame}`);
  }results.push({name:`dpr${dpr}-same-scene-acting-life-presentation`,status:'PASS',scope:'Production public renderer and actual decoded art presented on four room actors with paused clock; sequence frames are chosen explicitly, not autonomous AI behavior.'});}
(async()=>{browser=await fixture.chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-web-security']});fixture.setBrowser(browser);
  for(const dpr of [1,2]){const f=await fresh(dpr);try{assert.equal(await f.page.evaluate(()=>devicePixelRatio),dpr);await nativePixels(f.page,dpr);await selection(f.page,dpr);await gallery(f.page,dpr);assert.deepEqual(f.errors,[]);}finally{await f.page.close();}await walking(dpr);}
  assert.deepEqual(bindings(false),sourceSha256);for(const item of assetRecords)assert.equal(sha(fs.readFileSync(assetPath(item))),item.sha256,'Artwork changed during QA');if(manifest)assert.equal(sha(fs.readFileSync(manifestPath)),manifest.sha256,'Manifest changed during QA');
  const contactSheets=manifestData?.contactSheets||[];for(const contact of contactSheets)assert.equal(sha(fs.readFileSync(path.join(root,contact.path))),contact.sha256);
  const finalCaptures=captures,pngOptimization=null;
  assert.deepEqual(bindings(false),sourceSha256);if(manifest)assert.equal(sha(fs.readFileSync(manifestPath)),manifest.sha256);
  const report={schema:'one-piece-room-reserved-art-browser-qa/1',ok:true,previewOnly,status:'PASS',keys,dprs:[1,2],assetCount:assetRecords.length,manifest,contactSheets,results,captures:finalCaptures,pngOptimization,assets:assetRecords,sourceSha256,sourceNormalizedSha256,sourceHashNormalization:'UTF-8 decoded text; replace CRLF (\\r\\n) with LF (\\n) only; no other changes.',testScriptSha256:sha(fs.readFileSync(__filename)),fixtureOriginalSha256:sha(fs.readFileSync(helperPath)),fixtureEffectiveSha256:sha(source),humanAcceptance:false,canvasReadbackOriginBypass:true,autonomousLifeTickSuppressed:true,scope:'Actual headless Google Chrome DPR1/2 with real generated WebP and production renderer/navigation. Disposable browser disables web security only to permit readback of the isolated opui custom-scheme canvases. IPC and release flags isolated; autonomous life ticks suppressed so scripted real BFS routes stay deterministic. No physical-device, real-account, autonomous-scenario or deployment acceptance.'};fs.writeFileSync(path.join(out,'RESERVED_ART_BROWSER_QA.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({ok:true,previewOnly:report.previewOnly,checks:results.length,captures:captures.length,assetCount:assetRecords.length}));
})().catch(error=>{fs.writeFileSync(path.join(out,'FAILURE.json'),JSON.stringify({ok:false,error:error.stack,results},null,2));console.error(error.stack);process.exitCode=1;}).finally(async()=>{await browser?.close();});
